In [148]:
import json
import re
import pickle
import pandas as pd
import numpy as np

In [149]:
with open('LOCATION_TO_COUNTRY_MAP.pickle', 'rb') as handle:
    mapping = pickle.load(handle)

In [150]:
mapping

{'Manchester, England': 'England',
 'nan': 'None',
 'Villa Park': 'None',
 'Lagos, Nigeria': 'Nigeria',
 '75% OFF ': 'None',
 'ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑŸÖŸÜŸàÿ±ÿ©': 'Saudi Arabia',
 'London, England': 'England',
 'Somewhere ': 'None',
 'Cape Town, South Africa': 'South Africa',
 'Earth': 'None',
 'Beta, NC': 'USA',
 'ƒ∞stanbul, T√ºrkiye': 'Turkey',
 'Hedera hashgraph~ 0.0.3022395': 'None',
 'Check my Highlights for Gems:gem stone:': 'None',
 'Web 3': 'None',
 'Dubai, United Arab Emirates': 'United Arab Emirates',
 '127.0.0.1': 'None',
 'Linktree ‚Üí': 'None',
 'Polska': 'Poland',
 'Maryland, USA': 'USA',
 'Parody ': 'None',
 'Manchester': 'England',
 'Denver, CO': 'USA',
 'Hood By Air': 'None',
 'liverpool la ': 'England',
 'Worldwide': 'None',
 'London-Riyadh-LA': 'England',
 'Amsterdam': 'Netherlands',
 'Nigeria': 'Nigeria',
 'Las Vegas, Nevada': 'USA',
 '$RARE': 'None',
 'India': 'India',
 'Edo, Nigeria': 'Nigeria',
 'England, United Kingdom': 'England',
 'Melbourne, Victoria': 'Australia',
 'United Kingdom': 'United Kingdom',
 'Prayagraj, UP, India': 'India',
 'Dakar-Nairobi-Kigali-Cape Town': 'None',
 'USA': 'USA',
 'Jeddah, Kingdom of Saudi Arabi': 'Saudi Arabia',
 'Khakhala Village, Giyani :flag: South Africa:': 'South Africa',
 'Pune': 'India',
 'Canada': 'Canada',
 'Assam , India ': 'India',
 'United States': 'USA',
 'Heaven': 'None',
 'Throne Room ll Stadium ll Gym ': 'None',
 'Global': 'None',
 'still thinking about it': 'None',
 'Multichain': 'None',
 'Las Rozas de Madrid, Spain': 'Spain',
 'Louisiana, United States': 'USA',
 'Your Timeline': 'None',
 'Love and Light': 'None',
 'Ontario, Canada': 'Canada',
 'Mercury ': 'None',
 'Europe': 'None',
 'East Worldham, England': 'England',
 'Nairobi, Kenya': 'Kenya',
 'Pakistan': 'Pakistan',
 'free pavel': 'None',
 'Miami, FL': 'USA',
 'your heart ': 'None',
 'Kisumu | Vihiga | Nairobi ': 'Kenya',
 'Polokwane, South Africa': 'South Africa',
 'In My Mind': 'None',
 ':flag: Nigeria::flag: Canada:': 'None',
 'Everywhere': 'None',
 'United Kingdom ': 'United Kingdom',
 'Raiyani, Kenya': 'Kenya',
 'moi university :flag: Kenya:': 'Kenya',
 'Abuja, Nigeria': 'Nigeria',
 'Kampala, Uganda': 'Uganda',
 'Etihad ': 'None',
 'Kingdom Zone': 'None',
 'Kingston, Jamaica': 'Jamaica',
 'Johannesburg, South Africa': 'South Africa',
 'New York, USA': 'USA',
 'Kenya': 'Kenya',
 'England United Kingdom': 'England',
 ':flag: Finland:': 'Finland',
 'Kabale': 'Uganda',
 'London': 'England',
 'Florida, USA': 'USA',
 'Owerri North ': 'None',
 'Luxembourg ': 'Luxembourg',
 'City': 'None',
 'mjini': 'Tanzania',
 'England ': 'England',
 'Sandton, South Africa': 'South Africa',
 'Inside Human being': 'None',
 'In Between Places': 'None',
 'Delta, Nigeria': 'Nigeria',
 'Malaysia': 'Malaysia',
 'San Marcos, TX': 'USA',
 'South Africa': 'South Africa',
 'Josnes, France': 'France',
 'Turn on push notifications ': 'None',
 'RodriBallonDor': 'None',
 'earth': 'None',
 'Manchester (DM for Promos) ': 'England',
 'Port Harcourt of Nigeria': 'Nigeria',
 'n4n': 'None',
 'Sondu na Juja': 'Kenya',
 'World wide ': 'None',
 'RSA': 'South Africa',
 'Chelsea :blue heart:': 'England',
 'Turn on notis :bell:': 'None',
 'White Hart Lane': 'England',
 'Spain': 'Spain',
 'Morocco': 'Morocco',
 'Kingdom of Saudi Arabia': 'Saudi Arabia',
 'i': 'None',
 'Nairobi': 'Kenya',
 'The Dark Web': 'None',
 'XAUUSD': 'None',
 'Sea side': 'None',
 'next door': 'None',
 'Amsterdam, Nederland (Delulu)': 'Netherlands',
 'space & time': 'None',
 'Jos, Nigeria': 'Nigeria',
 'united states': 'USA',
 'Guangdong Guangzhou': 'China',
 'Ocean City, MD': 'USA',
 ':globe showing Europe-Africa: ': 'None',
 'WHEREVER MONEY IS, Earth': 'None',
 'On my post notification ': 'None',
 'Ottawa, Ontario': 'Canada',
 'Where the Money At': 'None',
 'Nowhere to be found': 'None',
 'Kuwait': 'Kuwait',
 'Brasil': 'Brazil',
 'Manchester ': 'England',
 'HFC | RMA': 'None',
 'New Jersey, USA': 'USA',
 'Moon, North Star, UNESCO, UEFA': 'None',
 'Munich ,german': 'Germany',
 "Depends on who's asking!!": 'None',
 '5th dimension': 'None',
 'Nigeria :flag: Nigeria:': 'Nigeria',
 'The Woodlands, TX': 'USA',
 'England': 'England',
 'Turn on notification :bell: ': 'None',
 'Brixton, England': 'England',
 'Boston ': 'USA',
 'Lagos Nigeria. ': 'Nigeria',
 'Wivenhoe': 'None',
 'Paris, France': 'France',
 'Kisii, Kenya': 'Kenya',
 'GOD first': 'None',
 'Uganda': 'Uganda',
 'Georgia, USA': 'USA',
 'On My Phone ': 'None',
 'Out Of Reach': 'None',
 'All America': 'USA',
 'Southport, England': 'England',
 'Kennington, England': 'England',
 'DM:envelope with arrow: - Collab:handshake::medium-dark skin tone: - Pub :dollar banknote:': 'None',
 'üåé:A button (blood type):üåëüåè :P button:üåã:A button (blood type):üåùüåè :globe showing Europe-Africa:': 'None',
 'Accra, Ghana': 'Ghana',
 ':fire::water wave:': 'None',
 'NearYourCity': 'None',
 'Vi·ªát Nam': 'Vietnam',
 ':helicopter:Agra :airplane: New Delhi :airplane arrival:Jaipur:house with garden:': 'India',
 'Dubai': 'UAE',
 'Jaipur, Rajasthan ': 'India',
 'Msg me on Snap:ghost:': 'None',
 'Lasgidi': 'Nigeria',
 'Westonaria ': 'South Africa',
 'Home': 'None',
 'In your head': 'None',
 'I am here': 'None',
 'Earth :globe showing Europe-Africa:': 'None',
 ' space :milky way: and Mars, Miami, USA': 'USA',
 'West Africa ': 'None',
 'K1': 'None',
 'from the river to the sea ': 'None',
 'LHR LAX JFK MCR': 'USA',
 'Milky Way': 'None',
 ':globe showing Americas:': 'None',
 ':goat:': 'None',
 'Metaverse, Web3, Remote': 'None',
 'Australia': 'Australia',
 '1cor16:7:red heart::black heart:': 'None',
 'Pretoria, Johannesburg': 'South Africa',
 'Barcelona, Espa√±a': 'Spain',
 'dm for promo': 'None',
 'Atlanta, GA': 'USA',
 'philly': 'USA',
 'Johannesburg': 'South Africa',
 'your phone': 'None',
 'Dublin City, Ireland': 'Ireland',
 'Camp nou :stadium:': 'None',
 'kent/liverpool': 'None',
 'Dar es Salaam, Tanzania': 'Tanzania',
 'outsider': 'None',
 'The Street': 'None',
 'somewhere ': 'None',
 'secret place of the most high': 'None',
 'United Arab Emirates': 'United Arab Emirates',
 'Grand Rapids, MI': 'USA',
 'e-available': 'None',
 'The emirates': 'UAE',
 'Earth ': 'None',
 'India ': 'India',
 'Angola': 'Angola',
 'knowhere ': 'None',
 'Dhaka, Bangladesh': 'Bangladesh',
 'Liverpool, England': 'England',
 'Doha, Qatar': 'Qatar',
 ':flag: United States: ': 'USA',
 'Chancellorite  :lion:': 'None',
 'Halo ring': 'None',
 'Somewhere in the World': 'None',
 'Swat, Pakistan': 'Pakistan',
 ':flag: Palestinian Territories::red heart:': 'Palestine',
 'Get Over ¬£500 In Free Bets! :backhand index pointing down:': 'None',
 'Web3': 'None',
 'Bangalore': 'India',
 'Leuven, Belgi√´ (BELGIUM).': 'Belgium',
 'From BrokenSea to Pond': 'None',
 'INSIDE MY HEAD ': 'None',
 'Mexico': 'Mexico',
 'London, UK:flag: Nigeria::flag: United Kingdom:': 'United Kingdom',
 'footytalkenquiries@gmail.com': 'None',
 'Dm for Notis': 'None',
 'Dm for Business :money bag:': 'None',
 ':envelope:DM for Business/ Promo': 'None',
 'Somewhere on planet Earth :globe showing Americas:': 'USA',
 'OT/Turn on notis :bell:': 'None',
 'Pep‚Äôs Bald Head': 'None',
 'in btw the stars ': 'None',
 'TMIHarini': 'None',
 'BLACK SITE': 'None',
 'Global :globe showing Americas:': 'USA',
 ':globe showing Europe-Africa:': 'None',
 'France Bordeaux ': 'France',
 'OSOGBO': 'Nigeria',
 'ÿßŸÑÿ±ŸäÿßÿØŸäÿ©': 'Saudi Arabia',
 'UK': 'England',
 'GUESS': 'None',
 'Kuwait-Qurtuba': 'Kuwait',
 'unknown': 'None',
 'San Cristobal, Tachira': 'Venezuela',
 'PLANET ‚Å¥‚Å∑': 'None',
 'Mars': 'None',
 'Turn on post notification :bell:': 'None',
 'Pretoria ': 'South Africa',
 'Couch': 'None',
 'Universe': 'None',
 ':round pushpin: Architecture :writing hand: medium-dark skin tone:': 'None',
 'Mpumalanga, South Africa': 'South Africa',
 '30bg resident ': 'None',
 'England uk ': 'England',
 'portharcourt': 'None',
 'in ur mind': 'None',
 'Nigeria, phone +2348060212017': 'Nigeria',
 'Nelspruit, South Africa': 'South Africa',
 'LINK :backhand index pointing right:i made my vip free ': 'None',
 'FREE OF :backhand index pointing right:': 'None',
 'Everywhere almost everytime.': 'None',
 'Pretoria, South Africa': 'South Africa',
 'Pottstown, PA': 'USA',
 'Where Opportunites Exist ': 'None',
 'Schiedam, Nederland': 'Netherlands',
 ':flag: Vietnam::flag: Sweden:': 'Vietnam',
 'TWITTER ': 'None',
 'Around the world ': 'None',
 'Kano, Nigeria': 'Nigeria',
 'Beside you ': 'None',
 'gasping for breath': 'None',
 'Available everywhere ': 'None',
 'rennes': 'France',
 ':flag: Mexico: 17': 'Mexico',
 'hell': 'None',
 'web3': 'None',
 'Durban, South Africa': 'South Africa',
 'Asgard': 'None',
 'worcester,ma': 'USA',
 'Cyprus ': 'Cyprus',
 'Auckland, NZ': 'New Zealand',
 'God‚Äôs hand ': 'None',
 'KER,IND': 'India',
 'Sao Paulo, Brazil': 'Brazil',
 ':flag: Sweden: & X Comment section.': 'Sweden',
 'Jharkhand, india': 'India',
 'Toronto, Ontario': 'Canada',
 'ap kay dil mein hamara account': 'None',
 '#YoungAndGodly..': 'None',
 'H√† N√¥i, Vi√®t Nam': 'Vietnam',
 'Mogadishu': 'Somalia',
 'Nyeri, Kenya': 'Kenya',
 'Twixt  Manchester and France': 'None',
 'In your head. ': 'None',
 'Goa': 'India',
 'heaven ': 'None',
 'Lagos': 'Nigeria',
 'Distrito Federal, M√©xico': 'Mexico',
 'city': 'None',
 ':briefcase:': 'None',
 'Austria': 'Austria',
 'Swindon, England': 'England',
 'sin city': 'USA',
 'Never mind ': 'None',
 'United States :flag: United States:': 'USA',
 'Dar es Salaam': 'Tanzania',
 'in your Heart :face with hand over mouth::mending heart:': 'None',
 'Ibadan/Abuja': 'Nigeria',
 'Nottingham, England': 'England',
 'Twitter': 'None',
 'Baltimore, MD': 'USA',
 'Lahore, Pakistan': 'Pakistan',
 'Abuja, Nigeria ': 'Nigeria',
 'grinding ': 'None',
 '299.792.458m/s': 'None',
 'Opulence ': 'None',
 'South West, England': 'England',
 'Manchester, UK': 'England',
 'pain. ': 'None',
 'Port Harcourt': 'Nigeria',
 'Preetinagar Madiyon lucknow': 'India',
 'turn on post notifications ': 'None',
 'East Africa :growing heart:': 'None',
 'My FREE OF :backhand index pointing right:': 'None',
 'polokwane ': 'South Africa',
 'Kirkland, WA': 'USA',
 "God's Child ": 'None',
 'Etihad Stadium:stadium:': 'None',
 'West Palm Beach, FL ': 'USA',
 'Twitter ': 'None',
 'Fan account ': 'None',
 'Camp Nou': 'Spain',
 'sowutuom': 'Ghana',
 'Cashapp ¬£1 :folded hands:': 'USA',
 'GET YOUR FREE TRIAL ON OF :backhand index pointing down:': 'USA',
 'Kumasi, Ghana': 'Ghana',
 'Telford, England': 'England',
 'UK ': 'England',
 'Turkey': 'Turkey',
 'Mombasa, Kenya': 'Kenya',
 'Malang': 'Indonesia',
 'No1 Ja‚Äômaar chase 8ta': 'None',
 'notis on 4 funny tweets:bellhop bell:': 'None',
 'ruto to sugoi': 'None',
 'Princess Land': 'None',
 'cloud 9': 'None',
 'Land ': 'None',
 'Madhya Pradesh, India': 'India',
 'Nyaribari Masaba': 'Kenya',
 'Ghana': 'Ghana',
 'football': 'None',
 'IN MY ZONE :drop of blood:': 'None',
 ':bell:  On Post Notification': 'None',
 'Ruhaama-Ntungamo :flag: Uganda: ': 'Uganda',
 'she/her ': 'None',
 'South East England': 'England',
 'Land down under :sun behind small cloud:': 'Australia',
 'Sphere': 'None',
 'Kaduna, Nigeria': 'Nigeria',
 'Karachi, Pakistan': 'Pakistan',
 'PortHarcourt, Nigeria': 'Nigeria',
 'around ': 'None',
 'Dange, ': 'None',
 'Los Angeles, CA': 'USA',
 'Red Earth 29, Saskatchewan': 'Canada',
 'Toronto ‚Å∂': 'Canada',
 'Bahawalpur': 'Pakistan',
 '#ÿ±ÿßÿ®ÿ∑ÿ©_ÿπÿ¥ÿßŸÇ_ŸáÿßŸÑÿßŸÜÿØ': 'None',
 'Kwa nyumba': 'Tanzania',
 'Bahrain': 'Bahrain',
 'TDE Headquarters': 'USA',
 'East London (DM for Promos)': 'England',
 'Istanbul :trophy: .. ': 'Turkey',
 'Blue Heart': 'None',
 'DM FOR THUMBNAIL PRICES': 'None',
 'Dm for promotions :blue heart:': 'None',
 '7th heaven': 'None',
 'Espagne': 'France',
 'Enugu': 'Nigeria',
 'That remains a mystery ': 'None',
 'Tema, Ghana': 'Ghana',
 'Ngong, Kenya': 'Kenya',
 'The EU': 'None',
 'Lucknow India :flag: India:': 'India',
 'Boston, MA': 'USA',
 'East': 'None',
 'Isingiro ': 'None',
 'Kisumu, Kenya': 'Kenya',
 'Nottingham': 'England',
 'Festac': 'Nigeria',
 ':flag: England:': 'England',
 'Pittsburgh': 'USA',
 'Faisalabad,Punjab, Pakistan': 'Pakistan',
 'Panipat Haryana India': 'India',
 'Holly Ridge, NC': 'USA',
 'North London': 'England',
 'Abuja ': 'Nigeria',
 'uganda': 'Uganda',
 'Trapped in my 0wn Cosmos:milky way:': 'None',
 'Punjab ': 'India',
 'Mars ': 'None',
 'Infinity Castle': 'None',
 'Ikeja Lagos': 'Nigeria',
 'IL√ê': 'Iceland',
 'Saliba, Saka & Mbappe': 'None',
 'Winchester, CA': 'USA',
 'ÿß⁄©€åŸÑ€í ŸæŸÜ ÿ≥€í ŸÖÿ≠ÿ®ÿ™ ÿ≥€å €ÅŸà⁄Ø€å €Å€í :raising hands:': 'Pakistan',
 'Bournemouth, England': 'England',
 'Up In The Skies. Elevated :woman in lotus position:': 'None',
 'The Etihad :flag: United Kingdom: ': 'United Kingdom',
 'Toronto': 'Canada',
 'Moon :upside-down face::smirking face:': 'None',
 'DM for Promos': 'None',
 'Asaba, Nigeria': 'Nigeria',
 'World :globe showing Europe-Africa:': 'None',
 'Huddersfield, England': 'England',
 'coatbridge': 'Scotland',
 'Denham Town': 'Jamaica',
 'Mare Tranquillitatis, Luna': 'None',
 'nigeria ': 'Nigeria',
 'DM for Business/ Promo': 'None',
 '6ix': 'Canada',
 'ÿØÿßŸÑÿ© ÿßŸÑŸÉŸàŸäÿ™': 'Kuwait',
 'OF :down arrow:': 'None',
 'Black Earth, WI': 'USA',
 'Baytu, Balotara ': 'None',
 'Greater Accra, Ghana': 'Ghana',
 'kawempe': 'Uganda',
 'Onitsha': 'Nigeria',
 'rsa': 'South Africa',
 'UNITED ARAB EMIRATES': 'United Arab Emirates',
 'where money is‚Ä¶': 'None',
 'dm 4 promo': 'None',
 'SOUTH AFRICA, MPU': 'South Africa',
 'Kwetu pazuri': 'Tanzania',
 'TopMG:index pointing up: light skin tone:': 'None',
 'Chuom': 'Vietnam',
 'New Delhi ': 'India',
 'Arewa,Nigeria': 'Nigeria',
 'Somewhere': 'None',
 'Rashford‚Äôs PR Team': 'None',
 'Tamale, Ghana': 'Ghana',
 'Greece': 'Greece',
 'B√† R·ªãa-V≈©ng T√†u, Vi·ªát Nam': 'Vietnam',
 'Vietnam': 'Vietnam',
 'Heaven ': 'None',
 'ùïè': 'None',
 'crypto': 'None',
 'Hyderabad': 'India',
 'Comps:victory hand:': 'None',
 'FL': 'USA',
 'Barranquilla, Colombia': 'Colombia',
 'Essex': 'England',
 'Heaven‚Äôs Synagogue :Japanese ‚Äúacceptable‚Äù button: ': 'None',
 'Sea': 'None',
 'Victoria Island, NIGERIA :flag: Nigeria: ': 'Nigeria',
 'Uttar Pradesh, Bharat': 'India',
 'No limits': 'None',
 'Kitui, Kenya': 'Kenya',
 'Honest //MCTID': 'None',
 'Moss Side, England': 'England',
 'Turn on notifs :bell:': 'None',
 'Lagos ': 'Nigeria',
 ' Canada': 'Canada',
 'SOMEWHERE': 'None',
 'Benoni, South Africa': 'South Africa',
 'Brussels, Belgium': 'Belgium',
 ' club of my heart :blue heart::flag: Kenya:': 'Kenya',
 'Joint Base Lewis-McChord, WA': 'USA',
 'Strand ': 'England',
 'Nigeria, Rivers, PHC.': 'Nigeria',
 'Brass, Nigeria': 'Nigeria',
 'Camp Nou :stadium:': 'None',
 'South Carolina, USA': 'USA',
 'nym/nyg/nyk/njd/unc/mc': 'None',
 '√úT: 6.46786,3.29173  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà': 'None',
 'Tanzania': 'Tanzania',
 'Decentralized world :globe with meridians:': 'None',
 'Washington DC': 'USA',
 'Jinja, Uganda': 'Uganda',
 'Space': 'None',
 'Where the money at': 'None',
 'ùöÉùöòùöô 1% :globe showing Europe-Africa:': 'None',
 '|| ': 'None',
 'Walsall, England': 'England',
 'world ': 'None',
 '≈Å√≥d≈∫, Polska': 'Poland',
 'hereforfun': 'None',
 'Norge': 'Norway',
 'We go run this town tonight :clinking glasses:': 'None',
 'join 70k+ lazy managers :right arrow:': 'None',
 'Alexandria, VA': 'USA',
 'Turn on my notification ': 'None',
 "God's plan": 'None',
 'ÌïúÌûàÌïôÎìú': 'South Korea',
 'Ilorin, Nigeria': 'Nigeria',
 'Leicester, England': 'England',
 ':fire:$DGDG DOGI DOGI:backhand index pointing right:buy here:backhand index pointing down:': 'None',
 'Warrington, England': 'England',
 'Tampa, FL': 'USA',
 'everywhere ': 'None',
 'Bayern, Deutschland': 'Germany',
 'Viet Nam': 'Vietnam',
 'Top 21 Inspiring Cyber Leader': 'None',
 'Trapping In Village ': 'None',
 'Home :house with garden:': 'None',
 'Explore Stats & Data :backhand index pointing right:': 'None',
 'funnyfootballbanter@gmail.com': 'None',
 'Montr√©al, Qu√©bec': 'Canada',
 'Pale Blue Dot / Liverpool': 'England',
 'Cobham': 'England',
 'Stamford Bridge, England': 'England',
 'Cross River, Nigeria': 'Nigeria',
 ':flag: United States::flag: United Kingdom:': 'USA',
 'Yorkshire and The Humber, England': 'England',
 'Guangzhou, China ': 'China',
 'Ho Chi Minh, Vietnam': 'Vietnam',
 'Somewhere in Africa': 'None',
 "In God's hands": 'None',
 'Manitoba Canada :flag: Canada:': 'Canada',
 'Denmark': 'Denmark',
 'ghana': 'Ghana',
 'Durban,South Africa': 'South Africa',
 'Austria - Carinthia': 'Austria',
 'Trenches': 'None',
 'DARK‚Ä¶': 'None',
 'lost': 'None',
 'In My Lane:globe showing Europe-Africa:': 'None',
 'All around ‚Ä†–Ω—î globe': 'None',
 'A kaya ': 'None',
 'HN': 'Honduras',
 'Light': 'None',
 'MCFC :blue heart:': 'None',
 'D12': 'None',
 'EARTH :globe showing Americas:': 'None',
 'Nigeria ': 'Nigeria',
 'Benin-City, Nigeria': 'Nigeria',
 ':flag: Morocco:': 'Morocco',
 'Everywhere ': 'None',
 'Borno - Kaduna ': 'Nigeria',
 'Republic of Mozambique': 'Mozambique',
 'World': 'None',
 'Follow me': 'None',
 'planet Earth': 'None',
 'Web 3.0 :round pushpin:': 'None',
 'santorini': 'Greece',
 'Planet of Queens :ringed planet: ': 'None',
 'Manchester, England ': 'England',
 'MANE.city': 'None',
 'New York, NY': 'USA',
 'Saudi Arabia': 'Saudi Arabia',
 'Anywhere & Everywhere': 'None',
 'on Earth ': 'None',
 'Metaverse ': 'None',
 'All over the world': 'None',
 ':burrito:': 'None',
 'London, LDN': 'England',
 'Kumasi-Ghana': 'Ghana',
 'Safe zone ': 'None',
 'DM FOR PROMOS': 'None',
 'London, England (UK)': 'England',
 "DM's are open": 'None',
 'Mumbai, New Delhi , Bangalore ': 'India',
 'Bogot√°, D.C., Colombia': 'Colombia',
 'web 3.0': 'None',
 'Mulot, Kenya': 'Kenya',
 'Sokoto, Nigeria': 'Nigeria',
 'in-the-trenches': 'None',
 'Port Harcourt,Rivers State, NG': 'Nigeria',
 'Afikpo, Nigeria': 'Nigeria',
 'invent a place where i belong': 'None',
 '..$': 'None',
 'Cuenca, Ecuador': 'Ecuador',
 ' ÿßŸÑŸáŸÑÿßŸÑ:blue heart:': 'None',
 'In the PORTAL': 'None',
 'Eastleigh': 'England',
 'Somewhere on pluto': 'None',
 '..': 'None',
 'Lost in thoughts': 'None',
 'Pashchim Muzaffarpur, India': 'India',
 'Somewhere on:globe showing Asia-Australia:': 'None',
 'LONDON': 'England',
 ':flag: United Kingdom:': 'England',
 ' catch a vibe ': 'None',
 'Emirates Stadium': 'England',
 'Toronto & London': 'Canada',
 'HQ': 'None',
 'Cotswolds, England, NewYork,US': 'USA',
 'Morogoro, Tanzania': 'Tanzania',
 'Kings Landing, Westeros': 'None',
 'Somewhere nice ': 'None',
 'My World ': 'None',
 'paris': 'France',
 'ùêèùêûùêöùêúùêû :victory hand:': 'None',
 'London ': 'England',
 'The swamp': 'None',
 'Somewhere in the world': 'None',
 'English united kingdom ': 'England',
 'Manchester :flag: England:': 'England',
 ':rainbow flag: Backup: @FootballReprt2': 'None',
 'Barcelona': 'Spain',
 'Wroclaw, Poland': 'Poland',
 'Where i no know': 'None',
 'Follow me ': 'None',
 'Sky': 'None',
 'Somewhere on Earth': 'None',
 'DM for Adverts, Trends &Promo ': 'None',
 'Surrey, South East England': 'England',
 'In the spirit Realm.': 'None',
 ':sun with face::sun with face::sun with face:': 'None',
 'Ontario, Canada ': 'Canada',
 'London, UK': 'England',
 'in a drainage ditch': 'None',
 'semarang, Indonesia': 'Indonesia',
 'Belo Horizonte, Brasil': 'Brazil',
 'Pakistan | England | Germany ': 'Pakistan',
 'Minna, Nigeria': 'Nigeria',
 'Southampton, England': 'England',
 'Earth:flag: Nigeria:': 'Nigeria',
 'Alaigbo ': 'Nigeria',
 'BUKOBA TANZANIA': 'Tanzania',
 'Airdrops Universe 11E11': 'None',
 'Kempton Park, South Africa': 'South Africa',
 '#International': 'None',
 'Chimpverse': 'None',
 'Looking for a UCL :clapping hands: medium-dark skin tone:': 'None',
 'Ngh·ªá An, Vietnam': 'Vietnam',
 'Right where I‚Äôm suppose to be ': 'None',
 'Sportybet ': 'None',
 'Munich, Bavaria': 'Germany',
 'United Kingdom :flag: United Kingdom:': 'United Kingdom',
 'Worldwide citizen': 'None',
 'ABJ:round pushpin:': 'Ivory Coast',
 'Usan, Scotland': 'Scotland',
 ':world map: :flag: Nigeria:': 'Nigeria',

In [151]:
with open('FAILED.pickle', 'rb') as handle:
    failed = pickle.load(handle)

In [152]:
failed

['[\n  {"location": "Port Harcourt, Nigeria", "country": "Nigeria"},\n  {"location": "Qatar", "country": "Qatar"},\n  {"location": "Santiago", "country": "Chile"},\n  {"location": "X", "country": "None"},\n  {"location": "Uyo akwa ibom Nigeria", "country": "Nigeria"},\n  {"location": ".", "country": "None"},\n  {"location": ":flag: France:\\U0001fa75:mantelpiece clock:", "country": "France"},\n  {"location": "Enugu State ", "country": "Nigeria"},\n  {"location": "Somewhere on earth ", "country": "None"},\n  {"location": "\\u0627\\u0644\\u0623\\u0631\\u062f \\u0645\\u0648\\u0642\\u0627\\u062c\\u0629", "country": "None"}\n]',
 '[{"location": ":flag: Ceuta & Melilla:", "country": "Spain"}, \n{"location": "Malindi, Kenya", "country": "Kenya"}, \n{"location": "Republic of Croatia", "country": "Croatia"}, \n{"location": "Commissions are open", "country": "None"}, \n{"location": "Metaverse", "country": "None"}, \n{"location": "In ur \\U0001fa77", "country": "None"}, \n{"location": "\\u1d6f\\u1d6a \\u1d6a\\u1d6c\\u1d6e", "country": "None"}, \n{"location": "70% off:two hearts::right arrow:", "country": "None"}, \n{"location": "Nam T·ª´ Li√™m HN", "country": "Vietnam"}, \n{"location": "Houston, TX", "country": "USA"}]',
 '[\n  {"location": "Germany ", "country": "Germany"},\n  {"location": "wonderland", "country": "None"},\n  {"location": "S\\u00e3o Paulo, Brasil", "country": "Brazil"},\n  {"location": "THE PLACE", "country": "None"},\n  {"location": "NY", "country": "USA"},\n  {"location": "Links\\u2014-", "country": "None"},\n  {"location": "Athgainistan", "country": "Afghanistan"},\n  {"location": \\"$Bitcoin", "country": "None"},\n  {"location": "Gilbert, AZ", "country": "USA"},\n  {"location": "Rosario, Argentina", "country": "Argentina"}\n]']

In [153]:
all_dicts = []

for string_data in failed:
    formatted_data = string_data.encode('utf-8').decode('unicode_escape')
    
    try:
        dict_list = json.loads(formatted_data)
        all_dicts.append(dict_list)
    except json.JSONDecodeError as e:
        print(f"Failed to parse JSON: {e}")

In [154]:
all_dicts

[[{'location': 'Port Harcourt, Nigeria', 'country': 'Nigeria'},
  {'location': 'Qatar', 'country': 'Qatar'},
  {'location': 'Santiago', 'country': 'Chile'},
  {'location': 'X', 'country': 'None'},
  {'location': 'Uyo akwa ibom Nigeria', 'country': 'Nigeria'},
  {'location': '.', 'country': 'None'},
  {'location': ':flag: France:\U0001fa75:mantelpiece clock:',
   'country': 'France'},
  {'location': 'Enugu State ', 'country': 'Nigeria'},
  {'location': 'Somewhere on earth ', 'country': 'None'},
  {'location': 'ÿßŸÑÿ£ÿ±ÿØ ŸÖŸàŸÇÿßÿ¨ÿ©', 'country': 'None'}],
 [{'location': ':flag: Ceuta & Melilla:', 'country': 'Spain'},
  {'location': 'Malindi, Kenya', 'country': 'Kenya'},
  {'location': 'Republic of Croatia', 'country': 'Croatia'},
  {'location': 'Commissions are open', 'country': 'None'},
  {'location': 'Metaverse', 'country': 'None'},
  {'location': 'In ur \U0001fa77', 'country': 'None'},
  {'location': '·µØ·µ™ ·µ™·µ¨·µÆ', 'country': 'None'},
  {'location': '70% off:two hearts::right arrow:', 'country': 'None'},
  {'location': 'Nam T√°¬ª¬´ Li√É¬™m HN', 'country': 'Vietnam'},
  {'location': 'Houston, TX', 'country': 'USA'}],
 [{'location': 'Germany ', 'country': 'Germany'},
  {'location': 'wonderland', 'country': 'None'},
  {'location': 'S√£o Paulo, Brasil', 'country': 'Brazil'},
  {'location': 'THE PLACE', 'country': 'None'},
  {'location': 'NY', 'country': 'USA'},
  {'location': 'Links‚Äî-', 'country': 'None'},
  {'location': 'Athgainistan', 'country': 'Afghanistan'},
  {'location': '$Bitcoin', 'country': 'None'},
  {'location': 'Gilbert, AZ', 'country': 'USA'},
  {'location': 'Rosario, Argentina', 'country': 'Argentina'}]]

In [155]:
all_dicts = [d for sublist in all_dicts for d in sublist]
all_dicts

[{'location': 'Port Harcourt, Nigeria', 'country': 'Nigeria'},
 {'location': 'Qatar', 'country': 'Qatar'},
 {'location': 'Santiago', 'country': 'Chile'},
 {'location': 'X', 'country': 'None'},
 {'location': 'Uyo akwa ibom Nigeria', 'country': 'Nigeria'},
 {'location': '.', 'country': 'None'},
 {'location': ':flag: France:\U0001fa75:mantelpiece clock:',
  'country': 'France'},
 {'location': 'Enugu State ', 'country': 'Nigeria'},
 {'location': 'Somewhere on earth ', 'country': 'None'},
 {'location': 'ÿßŸÑÿ£ÿ±ÿØ ŸÖŸàŸÇÿßÿ¨ÿ©', 'country': 'None'},
 {'location': ':flag: Ceuta & Melilla:', 'country': 'Spain'},
 {'location': 'Malindi, Kenya', 'country': 'Kenya'},
 {'location': 'Republic of Croatia', 'country': 'Croatia'},
 {'location': 'Commissions are open', 'country': 'None'},
 {'location': 'Metaverse', 'country': 'None'},
 {'location': 'In ur \U0001fa77', 'country': 'None'},
 {'location': '·µØ·µ™ ·µ™·µ¨·µÆ', 'country': 'None'},
 {'location': '70% off:two hearts::right arrow:', 'country': 'None'},
 {'location': 'Nam T√°¬ª¬´ Li√É¬™m HN', 'country': 'Vietnam'},
 {'location': 'Houston, TX', 'country': 'USA'},
 {'location': 'Germany ', 'country': 'Germany'},
 {'location': 'wonderland', 'country': 'None'},
 {'location': 'S√£o Paulo, Brasil', 'country': 'Brazil'},
 {'location': 'THE PLACE', 'country': 'None'},
 {'location': 'NY', 'country': 'USA'},
 {'location': 'Links‚Äî-', 'country': 'None'},
 {'location': 'Athgainistan', 'country': 'Afghanistan'},
 {'location': '$Bitcoin', 'country': 'None'},
 {'location': 'Gilbert, AZ', 'country': 'USA'},
 {'location': 'Rosario, Argentina', 'country': 'Argentina'}]

In [156]:
addl_dict = {}
for loc_dict in all_dicts: 
    addl_dict[loc_dict["location"]] = loc_dict["country"]
addl_dict

{'Port Harcourt, Nigeria': 'Nigeria',
 'Qatar': 'Qatar',
 'Santiago': 'Chile',
 'X': 'None',
 'Uyo akwa ibom Nigeria': 'Nigeria',
 '.': 'None',
 ':flag: France:\U0001fa75:mantelpiece clock:': 'France',
 'Enugu State ': 'Nigeria',
 'Somewhere on earth ': 'None',
 'ÿßŸÑÿ£ÿ±ÿØ ŸÖŸàŸÇÿßÿ¨ÿ©': 'None',
 ':flag: Ceuta & Melilla:': 'Spain',
 'Malindi, Kenya': 'Kenya',
 'Republic of Croatia': 'Croatia',
 'Commissions are open': 'None',
 'Metaverse': 'None',
 'In ur \U0001fa77': 'None',
 '·µØ·µ™ ·µ™·µ¨·µÆ': 'None',
 '70% off:two hearts::right arrow:': 'None',
 'Nam T√°¬ª¬´ Li√É¬™m HN': 'Vietnam',
 'Houston, TX': 'USA',
 'Germany ': 'Germany',
 'wonderland': 'None',
 'S√£o Paulo, Brasil': 'Brazil',
 'THE PLACE': 'None',
 'NY': 'USA',
 'Links‚Äî-': 'None',
 'Athgainistan': 'Afghanistan',
 '$Bitcoin': 'None',
 'Gilbert, AZ': 'USA',
 'Rosario, Argentina': 'Argentina'}

In [157]:
len(mapping), len(addl_dict)

(5670, 30)

In [158]:
mapping = mapping | addl_dict

In [159]:
len(mapping)

5670

In [160]:
mapping

{'Manchester, England': 'England',
 'nan': 'None',
 'Villa Park': 'None',
 'Lagos, Nigeria': 'Nigeria',
 '75% OFF ': 'None',
 'ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑŸÖŸÜŸàÿ±ÿ©': 'Saudi Arabia',
 'London, England': 'England',
 'Somewhere ': 'None',
 'Cape Town, South Africa': 'South Africa',
 'Earth': 'None',
 'Beta, NC': 'USA',
 'ƒ∞stanbul, T√ºrkiye': 'Turkey',
 'Hedera hashgraph~ 0.0.3022395': 'None',
 'Check my Highlights for Gems:gem stone:': 'None',
 'Web 3': 'None',
 'Dubai, United Arab Emirates': 'United Arab Emirates',
 '127.0.0.1': 'None',
 'Linktree ‚Üí': 'None',
 'Polska': 'Poland',
 'Maryland, USA': 'USA',
 'Parody ': 'None',
 'Manchester': 'England',
 'Denver, CO': 'USA',
 'Hood By Air': 'None',
 'liverpool la ': 'England',
 'Worldwide': 'None',
 'London-Riyadh-LA': 'England',
 'Amsterdam': 'Netherlands',
 'Nigeria': 'Nigeria',
 'Las Vegas, Nevada': 'USA',
 '$RARE': 'None',
 'India': 'India',
 'Edo, Nigeria': 'Nigeria',
 'England, United Kingdom': 'England',
 'Melbourne, Victoria': 'Australia',
 'United Kingdom': 'United Kingdom',
 'Prayagraj, UP, India': 'India',
 'Dakar-Nairobi-Kigali-Cape Town': 'None',
 'USA': 'USA',
 'Jeddah, Kingdom of Saudi Arabi': 'Saudi Arabia',
 'Khakhala Village, Giyani :flag: South Africa:': 'South Africa',
 'Pune': 'India',
 'Canada': 'Canada',
 'Assam , India ': 'India',
 'United States': 'USA',
 'Heaven': 'None',
 'Throne Room ll Stadium ll Gym ': 'None',
 'Global': 'None',
 'still thinking about it': 'None',
 'Multichain': 'None',
 'Las Rozas de Madrid, Spain': 'Spain',
 'Louisiana, United States': 'USA',
 'Your Timeline': 'None',
 'Love and Light': 'None',
 'Ontario, Canada': 'Canada',
 'Mercury ': 'None',
 'Europe': 'None',
 'East Worldham, England': 'England',
 'Nairobi, Kenya': 'Kenya',
 'Pakistan': 'Pakistan',
 'free pavel': 'None',
 'Miami, FL': 'USA',
 'your heart ': 'None',
 'Kisumu | Vihiga | Nairobi ': 'Kenya',
 'Polokwane, South Africa': 'South Africa',
 'In My Mind': 'None',
 ':flag: Nigeria::flag: Canada:': 'None',
 'Everywhere': 'None',
 'United Kingdom ': 'United Kingdom',
 'Raiyani, Kenya': 'Kenya',
 'moi university :flag: Kenya:': 'Kenya',
 'Abuja, Nigeria': 'Nigeria',
 'Kampala, Uganda': 'Uganda',
 'Etihad ': 'None',
 'Kingdom Zone': 'None',
 'Kingston, Jamaica': 'Jamaica',
 'Johannesburg, South Africa': 'South Africa',
 'New York, USA': 'USA',
 'Kenya': 'Kenya',
 'England United Kingdom': 'England',
 ':flag: Finland:': 'Finland',
 'Kabale': 'Uganda',
 'London': 'England',
 'Florida, USA': 'USA',
 'Owerri North ': 'None',
 'Luxembourg ': 'Luxembourg',
 'City': 'None',
 'mjini': 'Tanzania',
 'England ': 'England',
 'Sandton, South Africa': 'South Africa',
 'Inside Human being': 'None',
 'In Between Places': 'None',
 'Delta, Nigeria': 'Nigeria',
 'Malaysia': 'Malaysia',
 'San Marcos, TX': 'USA',
 'South Africa': 'South Africa',
 'Josnes, France': 'France',
 'Turn on push notifications ': 'None',
 'RodriBallonDor': 'None',
 'earth': 'None',
 'Manchester (DM for Promos) ': 'England',
 'Port Harcourt of Nigeria': 'Nigeria',
 'n4n': 'None',
 'Sondu na Juja': 'Kenya',
 'World wide ': 'None',
 'RSA': 'South Africa',
 'Chelsea :blue heart:': 'England',
 'Turn on notis :bell:': 'None',
 'White Hart Lane': 'England',
 'Spain': 'Spain',
 'Morocco': 'Morocco',
 'Kingdom of Saudi Arabia': 'Saudi Arabia',
 'i': 'None',
 'Nairobi': 'Kenya',
 'The Dark Web': 'None',
 'XAUUSD': 'None',
 'Sea side': 'None',
 'next door': 'None',
 'Amsterdam, Nederland (Delulu)': 'Netherlands',
 'space & time': 'None',
 'Jos, Nigeria': 'Nigeria',
 'united states': 'USA',
 'Guangdong Guangzhou': 'China',
 'Ocean City, MD': 'USA',
 ':globe showing Europe-Africa: ': 'None',
 'WHEREVER MONEY IS, Earth': 'None',
 'On my post notification ': 'None',
 'Ottawa, Ontario': 'Canada',
 'Where the Money At': 'None',
 'Nowhere to be found': 'None',
 'Kuwait': 'Kuwait',
 'Brasil': 'Brazil',
 'Manchester ': 'England',
 'HFC | RMA': 'None',
 'New Jersey, USA': 'USA',
 'Moon, North Star, UNESCO, UEFA': 'None',
 'Munich ,german': 'Germany',
 "Depends on who's asking!!": 'None',
 '5th dimension': 'None',
 'Nigeria :flag: Nigeria:': 'Nigeria',
 'The Woodlands, TX': 'USA',
 'England': 'England',
 'Turn on notification :bell: ': 'None',
 'Brixton, England': 'England',
 'Boston ': 'USA',
 'Lagos Nigeria. ': 'Nigeria',
 'Wivenhoe': 'None',
 'Paris, France': 'France',
 'Kisii, Kenya': 'Kenya',
 'GOD first': 'None',
 'Uganda': 'Uganda',
 'Georgia, USA': 'USA',
 'On My Phone ': 'None',
 'Out Of Reach': 'None',
 'All America': 'USA',
 'Southport, England': 'England',
 'Kennington, England': 'England',
 'DM:envelope with arrow: - Collab:handshake::medium-dark skin tone: - Pub :dollar banknote:': 'None',
 'üåé:A button (blood type):üåëüåè :P button:üåã:A button (blood type):üåùüåè :globe showing Europe-Africa:': 'None',
 'Accra, Ghana': 'Ghana',
 ':fire::water wave:': 'None',
 'NearYourCity': 'None',
 'Vi·ªát Nam': 'Vietnam',
 ':helicopter:Agra :airplane: New Delhi :airplane arrival:Jaipur:house with garden:': 'India',
 'Dubai': 'UAE',
 'Jaipur, Rajasthan ': 'India',
 'Msg me on Snap:ghost:': 'None',
 'Lasgidi': 'Nigeria',
 'Westonaria ': 'South Africa',
 'Home': 'None',
 'In your head': 'None',
 'I am here': 'None',
 'Earth :globe showing Europe-Africa:': 'None',
 ' space :milky way: and Mars, Miami, USA': 'USA',
 'West Africa ': 'None',
 'K1': 'None',
 'from the river to the sea ': 'None',
 'LHR LAX JFK MCR': 'USA',
 'Milky Way': 'None',
 ':globe showing Americas:': 'None',
 ':goat:': 'None',
 'Metaverse, Web3, Remote': 'None',
 'Australia': 'Australia',
 '1cor16:7:red heart::black heart:': 'None',
 'Pretoria, Johannesburg': 'South Africa',
 'Barcelona, Espa√±a': 'Spain',
 'dm for promo': 'None',
 'Atlanta, GA': 'USA',
 'philly': 'USA',
 'Johannesburg': 'South Africa',
 'your phone': 'None',
 'Dublin City, Ireland': 'Ireland',
 'Camp nou :stadium:': 'None',
 'kent/liverpool': 'None',
 'Dar es Salaam, Tanzania': 'Tanzania',
 'outsider': 'None',
 'The Street': 'None',
 'somewhere ': 'None',
 'secret place of the most high': 'None',
 'United Arab Emirates': 'United Arab Emirates',
 'Grand Rapids, MI': 'USA',
 'e-available': 'None',
 'The emirates': 'UAE',
 'Earth ': 'None',
 'India ': 'India',
 'Angola': 'Angola',
 'knowhere ': 'None',
 'Dhaka, Bangladesh': 'Bangladesh',
 'Liverpool, England': 'England',
 'Doha, Qatar': 'Qatar',
 ':flag: United States: ': 'USA',
 'Chancellorite  :lion:': 'None',
 'Halo ring': 'None',
 'Somewhere in the World': 'None',
 'Swat, Pakistan': 'Pakistan',
 ':flag: Palestinian Territories::red heart:': 'Palestine',
 'Get Over ¬£500 In Free Bets! :backhand index pointing down:': 'None',
 'Web3': 'None',
 'Bangalore': 'India',
 'Leuven, Belgi√´ (BELGIUM).': 'Belgium',
 'From BrokenSea to Pond': 'None',
 'INSIDE MY HEAD ': 'None',
 'Mexico': 'Mexico',
 'London, UK:flag: Nigeria::flag: United Kingdom:': 'United Kingdom',
 'footytalkenquiries@gmail.com': 'None',
 'Dm for Notis': 'None',
 'Dm for Business :money bag:': 'None',
 ':envelope:DM for Business/ Promo': 'None',
 'Somewhere on planet Earth :globe showing Americas:': 'USA',
 'OT/Turn on notis :bell:': 'None',
 'Pep‚Äôs Bald Head': 'None',
 'in btw the stars ': 'None',
 'TMIHarini': 'None',
 'BLACK SITE': 'None',
 'Global :globe showing Americas:': 'USA',
 ':globe showing Europe-Africa:': 'None',
 'France Bordeaux ': 'France',
 'OSOGBO': 'Nigeria',
 'ÿßŸÑÿ±ŸäÿßÿØŸäÿ©': 'Saudi Arabia',
 'UK': 'England',
 'GUESS': 'None',
 'Kuwait-Qurtuba': 'Kuwait',
 'unknown': 'None',
 'San Cristobal, Tachira': 'Venezuela',
 'PLANET ‚Å¥‚Å∑': 'None',
 'Mars': 'None',
 'Turn on post notification :bell:': 'None',
 'Pretoria ': 'South Africa',
 'Couch': 'None',
 'Universe': 'None',
 ':round pushpin: Architecture :writing hand: medium-dark skin tone:': 'None',
 'Mpumalanga, South Africa': 'South Africa',
 '30bg resident ': 'None',
 'England uk ': 'England',
 'portharcourt': 'None',
 'in ur mind': 'None',
 'Nigeria, phone +2348060212017': 'Nigeria',
 'Nelspruit, South Africa': 'South Africa',
 'LINK :backhand index pointing right:i made my vip free ': 'None',
 'FREE OF :backhand index pointing right:': 'None',
 'Everywhere almost everytime.': 'None',
 'Pretoria, South Africa': 'South Africa',
 'Pottstown, PA': 'USA',
 'Where Opportunites Exist ': 'None',
 'Schiedam, Nederland': 'Netherlands',
 ':flag: Vietnam::flag: Sweden:': 'Vietnam',
 'TWITTER ': 'None',
 'Around the world ': 'None',
 'Kano, Nigeria': 'Nigeria',
 'Beside you ': 'None',
 'gasping for breath': 'None',
 'Available everywhere ': 'None',
 'rennes': 'France',
 ':flag: Mexico: 17': 'Mexico',
 'hell': 'None',
 'web3': 'None',
 'Durban, South Africa': 'South Africa',
 'Asgard': 'None',
 'worcester,ma': 'USA',
 'Cyprus ': 'Cyprus',
 'Auckland, NZ': 'New Zealand',
 'God‚Äôs hand ': 'None',
 'KER,IND': 'India',
 'Sao Paulo, Brazil': 'Brazil',
 ':flag: Sweden: & X Comment section.': 'Sweden',
 'Jharkhand, india': 'India',
 'Toronto, Ontario': 'Canada',
 'ap kay dil mein hamara account': 'None',
 '#YoungAndGodly..': 'None',
 'H√† N√¥i, Vi√®t Nam': 'Vietnam',
 'Mogadishu': 'Somalia',
 'Nyeri, Kenya': 'Kenya',
 'Twixt  Manchester and France': 'None',
 'In your head. ': 'None',
 'Goa': 'India',
 'heaven ': 'None',
 'Lagos': 'Nigeria',
 'Distrito Federal, M√©xico': 'Mexico',
 'city': 'None',
 ':briefcase:': 'None',
 'Austria': 'Austria',
 'Swindon, England': 'England',
 'sin city': 'USA',
 'Never mind ': 'None',
 'United States :flag: United States:': 'USA',
 'Dar es Salaam': 'Tanzania',
 'in your Heart :face with hand over mouth::mending heart:': 'None',
 'Ibadan/Abuja': 'Nigeria',
 'Nottingham, England': 'England',
 'Twitter': 'None',
 'Baltimore, MD': 'USA',
 'Lahore, Pakistan': 'Pakistan',
 'Abuja, Nigeria ': 'Nigeria',
 'grinding ': 'None',
 '299.792.458m/s': 'None',
 'Opulence ': 'None',
 'South West, England': 'England',
 'Manchester, UK': 'England',
 'pain. ': 'None',
 'Port Harcourt': 'Nigeria',
 'Preetinagar Madiyon lucknow': 'India',
 'turn on post notifications ': 'None',
 'East Africa :growing heart:': 'None',
 'My FREE OF :backhand index pointing right:': 'None',
 'polokwane ': 'South Africa',
 'Kirkland, WA': 'USA',
 "God's Child ": 'None',
 'Etihad Stadium:stadium:': 'None',
 'West Palm Beach, FL ': 'USA',
 'Twitter ': 'None',
 'Fan account ': 'None',
 'Camp Nou': 'Spain',
 'sowutuom': 'Ghana',
 'Cashapp ¬£1 :folded hands:': 'USA',
 'GET YOUR FREE TRIAL ON OF :backhand index pointing down:': 'USA',
 'Kumasi, Ghana': 'Ghana',
 'Telford, England': 'England',
 'UK ': 'England',
 'Turkey': 'Turkey',
 'Mombasa, Kenya': 'Kenya',
 'Malang': 'Indonesia',
 'No1 Ja‚Äômaar chase 8ta': 'None',
 'notis on 4 funny tweets:bellhop bell:': 'None',
 'ruto to sugoi': 'None',
 'Princess Land': 'None',
 'cloud 9': 'None',
 'Land ': 'None',
 'Madhya Pradesh, India': 'India',
 'Nyaribari Masaba': 'Kenya',
 'Ghana': 'Ghana',
 'football': 'None',
 'IN MY ZONE :drop of blood:': 'None',
 ':bell:  On Post Notification': 'None',
 'Ruhaama-Ntungamo :flag: Uganda: ': 'Uganda',
 'she/her ': 'None',
 'South East England': 'England',
 'Land down under :sun behind small cloud:': 'Australia',
 'Sphere': 'None',
 'Kaduna, Nigeria': 'Nigeria',
 'Karachi, Pakistan': 'Pakistan',
 'PortHarcourt, Nigeria': 'Nigeria',
 'around ': 'None',
 'Dange, ': 'None',
 'Los Angeles, CA': 'USA',
 'Red Earth 29, Saskatchewan': 'Canada',
 'Toronto ‚Å∂': 'Canada',
 'Bahawalpur': 'Pakistan',
 '#ÿ±ÿßÿ®ÿ∑ÿ©_ÿπÿ¥ÿßŸÇ_ŸáÿßŸÑÿßŸÜÿØ': 'None',
 'Kwa nyumba': 'Tanzania',
 'Bahrain': 'Bahrain',
 'TDE Headquarters': 'USA',
 'East London (DM for Promos)': 'England',
 'Istanbul :trophy: .. ': 'Turkey',
 'Blue Heart': 'None',
 'DM FOR THUMBNAIL PRICES': 'None',
 'Dm for promotions :blue heart:': 'None',
 '7th heaven': 'None',
 'Espagne': 'France',
 'Enugu': 'Nigeria',
 'That remains a mystery ': 'None',
 'Tema, Ghana': 'Ghana',
 'Ngong, Kenya': 'Kenya',
 'The EU': 'None',
 'Lucknow India :flag: India:': 'India',
 'Boston, MA': 'USA',
 'East': 'None',
 'Isingiro ': 'None',
 'Kisumu, Kenya': 'Kenya',
 'Nottingham': 'England',
 'Festac': 'Nigeria',
 ':flag: England:': 'England',
 'Pittsburgh': 'USA',
 'Faisalabad,Punjab, Pakistan': 'Pakistan',
 'Panipat Haryana India': 'India',
 'Holly Ridge, NC': 'USA',
 'North London': 'England',
 'Abuja ': 'Nigeria',
 'uganda': 'Uganda',
 'Trapped in my 0wn Cosmos:milky way:': 'None',
 'Punjab ': 'India',
 'Mars ': 'None',
 'Infinity Castle': 'None',
 'Ikeja Lagos': 'Nigeria',
 'IL√ê': 'Iceland',
 'Saliba, Saka & Mbappe': 'None',
 'Winchester, CA': 'USA',
 'ÿß⁄©€åŸÑ€í ŸæŸÜ ÿ≥€í ŸÖÿ≠ÿ®ÿ™ ÿ≥€å €ÅŸà⁄Ø€å €Å€í :raising hands:': 'Pakistan',
 'Bournemouth, England': 'England',
 'Up In The Skies. Elevated :woman in lotus position:': 'None',
 'The Etihad :flag: United Kingdom: ': 'United Kingdom',
 'Toronto': 'Canada',
 'Moon :upside-down face::smirking face:': 'None',
 'DM for Promos': 'None',
 'Asaba, Nigeria': 'Nigeria',
 'World :globe showing Europe-Africa:': 'None',
 'Huddersfield, England': 'England',
 'coatbridge': 'Scotland',
 'Denham Town': 'Jamaica',
 'Mare Tranquillitatis, Luna': 'None',
 'nigeria ': 'Nigeria',
 'DM for Business/ Promo': 'None',
 '6ix': 'Canada',
 'ÿØÿßŸÑÿ© ÿßŸÑŸÉŸàŸäÿ™': 'Kuwait',
 'OF :down arrow:': 'None',
 'Black Earth, WI': 'USA',
 'Baytu, Balotara ': 'None',
 'Greater Accra, Ghana': 'Ghana',
 'kawempe': 'Uganda',
 'Onitsha': 'Nigeria',
 'rsa': 'South Africa',
 'UNITED ARAB EMIRATES': 'United Arab Emirates',
 'where money is‚Ä¶': 'None',
 'dm 4 promo': 'None',
 'SOUTH AFRICA, MPU': 'South Africa',
 'Kwetu pazuri': 'Tanzania',
 'TopMG:index pointing up: light skin tone:': 'None',
 'Chuom': 'Vietnam',
 'New Delhi ': 'India',
 'Arewa,Nigeria': 'Nigeria',
 'Somewhere': 'None',
 'Rashford‚Äôs PR Team': 'None',
 'Tamale, Ghana': 'Ghana',
 'Greece': 'Greece',
 'B√† R·ªãa-V≈©ng T√†u, Vi·ªát Nam': 'Vietnam',
 'Vietnam': 'Vietnam',
 'Heaven ': 'None',
 'ùïè': 'None',
 'crypto': 'None',
 'Hyderabad': 'India',
 'Comps:victory hand:': 'None',
 'FL': 'USA',
 'Barranquilla, Colombia': 'Colombia',
 'Essex': 'England',
 'Heaven‚Äôs Synagogue :Japanese ‚Äúacceptable‚Äù button: ': 'None',
 'Sea': 'None',
 'Victoria Island, NIGERIA :flag: Nigeria: ': 'Nigeria',
 'Uttar Pradesh, Bharat': 'India',
 'No limits': 'None',
 'Kitui, Kenya': 'Kenya',
 'Honest //MCTID': 'None',
 'Moss Side, England': 'England',
 'Turn on notifs :bell:': 'None',
 'Lagos ': 'Nigeria',
 ' Canada': 'Canada',
 'SOMEWHERE': 'None',
 'Benoni, South Africa': 'South Africa',
 'Brussels, Belgium': 'Belgium',
 ' club of my heart :blue heart::flag: Kenya:': 'Kenya',
 'Joint Base Lewis-McChord, WA': 'USA',
 'Strand ': 'England',
 'Nigeria, Rivers, PHC.': 'Nigeria',
 'Brass, Nigeria': 'Nigeria',
 'Camp Nou :stadium:': 'None',
 'South Carolina, USA': 'USA',
 'nym/nyg/nyk/njd/unc/mc': 'None',
 '√úT: 6.46786,3.29173  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà': 'None',
 'Tanzania': 'Tanzania',
 'Decentralized world :globe with meridians:': 'None',
 'Washington DC': 'USA',
 'Jinja, Uganda': 'Uganda',
 'Space': 'None',
 'Where the money at': 'None',
 'ùöÉùöòùöô 1% :globe showing Europe-Africa:': 'None',
 '|| ': 'None',
 'Walsall, England': 'England',
 'world ': 'None',
 '≈Å√≥d≈∫, Polska': 'Poland',
 'hereforfun': 'None',
 'Norge': 'Norway',
 'We go run this town tonight :clinking glasses:': 'None',
 'join 70k+ lazy managers :right arrow:': 'None',
 'Alexandria, VA': 'USA',
 'Turn on my notification ': 'None',
 "God's plan": 'None',
 'ÌïúÌûàÌïôÎìú': 'South Korea',
 'Ilorin, Nigeria': 'Nigeria',
 'Leicester, England': 'England',
 ':fire:$DGDG DOGI DOGI:backhand index pointing right:buy here:backhand index pointing down:': 'None',
 'Warrington, England': 'England',
 'Tampa, FL': 'USA',
 'everywhere ': 'None',
 'Bayern, Deutschland': 'Germany',
 'Viet Nam': 'Vietnam',
 'Top 21 Inspiring Cyber Leader': 'None',
 'Trapping In Village ': 'None',
 'Home :house with garden:': 'None',
 'Explore Stats & Data :backhand index pointing right:': 'None',
 'funnyfootballbanter@gmail.com': 'None',
 'Montr√©al, Qu√©bec': 'Canada',
 'Pale Blue Dot / Liverpool': 'England',
 'Cobham': 'England',
 'Stamford Bridge, England': 'England',
 'Cross River, Nigeria': 'Nigeria',
 ':flag: United States::flag: United Kingdom:': 'USA',
 'Yorkshire and The Humber, England': 'England',
 'Guangzhou, China ': 'China',
 'Ho Chi Minh, Vietnam': 'Vietnam',
 'Somewhere in Africa': 'None',
 "In God's hands": 'None',
 'Manitoba Canada :flag: Canada:': 'Canada',
 'Denmark': 'Denmark',
 'ghana': 'Ghana',
 'Durban,South Africa': 'South Africa',
 'Austria - Carinthia': 'Austria',
 'Trenches': 'None',
 'DARK‚Ä¶': 'None',
 'lost': 'None',
 'In My Lane:globe showing Europe-Africa:': 'None',
 'All around ‚Ä†–Ω—î globe': 'None',
 'A kaya ': 'None',
 'HN': 'Honduras',
 'Light': 'None',
 'MCFC :blue heart:': 'None',
 'D12': 'None',
 'EARTH :globe showing Americas:': 'None',
 'Nigeria ': 'Nigeria',
 'Benin-City, Nigeria': 'Nigeria',
 ':flag: Morocco:': 'Morocco',
 'Everywhere ': 'None',
 'Borno - Kaduna ': 'Nigeria',
 'Republic of Mozambique': 'Mozambique',
 'World': 'None',
 'Follow me': 'None',
 'planet Earth': 'None',
 'Web 3.0 :round pushpin:': 'None',
 'santorini': 'Greece',
 'Planet of Queens :ringed planet: ': 'None',
 'Manchester, England ': 'England',
 'MANE.city': 'None',
 'New York, NY': 'USA',
 'Saudi Arabia': 'Saudi Arabia',
 'Anywhere & Everywhere': 'None',
 'on Earth ': 'None',
 'Metaverse ': 'None',
 'All over the world': 'None',
 ':burrito:': 'None',
 'London, LDN': 'England',
 'Kumasi-Ghana': 'Ghana',
 'Safe zone ': 'None',
 'DM FOR PROMOS': 'None',
 'London, England (UK)': 'England',
 "DM's are open": 'None',
 'Mumbai, New Delhi , Bangalore ': 'India',
 'Bogot√°, D.C., Colombia': 'Colombia',
 'web 3.0': 'None',
 'Mulot, Kenya': 'Kenya',
 'Sokoto, Nigeria': 'Nigeria',
 'in-the-trenches': 'None',
 'Port Harcourt,Rivers State, NG': 'Nigeria',
 'Afikpo, Nigeria': 'Nigeria',
 'invent a place where i belong': 'None',
 '..$': 'None',
 'Cuenca, Ecuador': 'Ecuador',
 ' ÿßŸÑŸáŸÑÿßŸÑ:blue heart:': 'None',
 'In the PORTAL': 'None',
 'Eastleigh': 'England',
 'Somewhere on pluto': 'None',
 '..': 'None',
 'Lost in thoughts': 'None',
 'Pashchim Muzaffarpur, India': 'India',
 'Somewhere on:globe showing Asia-Australia:': 'None',
 'LONDON': 'England',
 ':flag: United Kingdom:': 'England',
 ' catch a vibe ': 'None',
 'Emirates Stadium': 'England',
 'Toronto & London': 'Canada',
 'HQ': 'None',
 'Cotswolds, England, NewYork,US': 'USA',
 'Morogoro, Tanzania': 'Tanzania',
 'Kings Landing, Westeros': 'None',
 'Somewhere nice ': 'None',
 'My World ': 'None',
 'paris': 'France',
 'ùêèùêûùêöùêúùêû :victory hand:': 'None',
 'London ': 'England',
 'The swamp': 'None',
 'Somewhere in the world': 'None',
 'English united kingdom ': 'England',
 'Manchester :flag: England:': 'England',
 ':rainbow flag: Backup: @FootballReprt2': 'None',
 'Barcelona': 'Spain',
 'Wroclaw, Poland': 'Poland',
 'Where i no know': 'None',
 'Follow me ': 'None',
 'Sky': 'None',
 'Somewhere on Earth': 'None',
 'DM for Adverts, Trends &Promo ': 'None',
 'Surrey, South East England': 'England',
 'In the spirit Realm.': 'None',
 ':sun with face::sun with face::sun with face:': 'None',
 'Ontario, Canada ': 'Canada',
 'London, UK': 'England',
 'in a drainage ditch': 'None',
 'semarang, Indonesia': 'Indonesia',
 'Belo Horizonte, Brasil': 'Brazil',
 'Pakistan | England | Germany ': 'Pakistan',
 'Minna, Nigeria': 'Nigeria',
 'Southampton, England': 'England',
 'Earth:flag: Nigeria:': 'Nigeria',
 'Alaigbo ': 'Nigeria',
 'BUKOBA TANZANIA': 'Tanzania',
 'Airdrops Universe 11E11': 'None',
 'Kempton Park, South Africa': 'South Africa',
 '#International': 'None',
 'Chimpverse': 'None',
 'Looking for a UCL :clapping hands: medium-dark skin tone:': 'None',
 'Ngh·ªá An, Vietnam': 'Vietnam',
 'Right where I‚Äôm suppose to be ': 'None',
 'Sportybet ': 'None',
 'Munich, Bavaria': 'Germany',
 'United Kingdom :flag: United Kingdom:': 'United Kingdom',
 'Worldwide citizen': 'None',
 'ABJ:round pushpin:': 'Ivory Coast',
 'Usan, Scotland': 'Scotland',
 ':world map: :flag: Nigeria:': 'Nigeria',

In [161]:
has_country = {k: v for k, v in mapping.items() if v != "None"}

In [162]:
len(has_country)

3679

In [163]:
replies = pd.read_csv("/home/jasmine/PROJECTS/research/data_scrape/REPLIES_FINAL.csv")
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,109.0,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,6970.0,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,5293573.0,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,...,2423724.0,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,452.0,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,57.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,0.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,2038.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,94.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,312.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc

In [164]:
replies["user_country"] = None

In [165]:
replies["user_country"] = replies["user_location"].map(mapping)

In [166]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,England
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,...,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,None
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,Nigeria
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,USA

In [167]:
replies[replies["user_country"] != "None"]

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,England
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,United Kingdom
5,2024-05-14 21:05:08+00:00,@ManCity @okx üòéüòé https://t.co/zHij94Gj1q,1.790489e+18,NancyIsime678,2023-12-19 02:47:51+00:00,qme,9.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,Nigeria
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,USA

In [168]:
no_country = replies[replies["user_country"].isna()]
no_country

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
5,2024-05-14 21:05:08+00:00,@ManCity @okx üòéüòé https://t.co/zHij94Gj1q,1.790489e+18,NancyIsime678,2023-12-19 02:47:51+00:00,qme,9.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
6,2024-05-14 21:05:51+00:00,@ManCity @okx Lol forget Arsenal fans\nWe got ...,1.790489e+18,OlusammyA,2024-02-26 13:56:50+00:00,en,6.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
10,2024-05-14 20:52:18+00:00,@ManCity Just repost https://t.co/TBy1PuV3D7,1.790485e+18,TheChelseaForum,2014-10-02 15:42:00+00:00,en,12.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790485181561753856,2,0:2,spursofficial,mancity,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79567,2023-08-13 07:41:53+00:00,@SheffieldUnited Ollie inaction,1.690630e+18,tokennorthsufc,2014-03-22 20:56:59+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690370526500241408,0,0:0,sheffieldunited,cpfc,NaN
79568,2023-08-12 14:25:25+00:00,@SheffieldUnited Miles off tbf,1.690369e+18,MattUTB,2018-02-06 04:23:19+00:00,en,1.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690368822346158080,0,0:0,sheffieldunited,cpfc,NaN
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN

In [169]:
no_country[no_country["place"].isna()]

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
5,2024-05-14 21:05:08+00:00,@ManCity @okx üòéüòé https://t.co/zHij94Gj1q,1.790489e+18,NancyIsime678,2023-12-19 02:47:51+00:00,qme,9.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
6,2024-05-14 21:05:51+00:00,@ManCity @okx Lol forget Arsenal fans\nWe got ...,1.790489e+18,OlusammyA,2024-02-26 13:56:50+00:00,en,6.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN
10,2024-05-14 20:52:18+00:00,@ManCity Just repost https://t.co/TBy1PuV3D7,1.790485e+18,TheChelseaForum,2014-10-02 15:42:00+00:00,en,12.0,NaN,NaN,NaN,...,False,True,NaN,2ba17e6d,1790485181561753856,2,0:2,spursofficial,mancity,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79567,2023-08-13 07:41:53+00:00,@SheffieldUnited Ollie inaction,1.690630e+18,tokennorthsufc,2014-03-22 20:56:59+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690370526500241408,0,0:0,sheffieldunited,cpfc,NaN
79568,2023-08-12 14:25:25+00:00,@SheffieldUnited Miles off tbf,1.690369e+18,MattUTB,2018-02-06 04:23:19+00:00,en,1.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690368822346158080,0,0:0,sheffieldunited,cpfc,NaN
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN

In [170]:
no_country[~no_country["place"].isna()]

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country
438,2024-05-04 18:13:27+00:00,@ManCity 6eheheiiuu,1.786821e+18,macsimon22,2021-03-13 12:19:54+00:00,pt,0.0,"Place(id='000763a81141ab85', fullName='Maidugu...",NaN,"Lagos St, Maiduguri, Borno, Ni",...,False,False,NaN,5a9032bf,1786821260212609479,4,5:1,mancity,wolves,NaN
1620,2024-04-03 20:46:12+00:00,@ManCity @PhilFoden üíôüíôüíô https://t.co/jNtAAO3SO8,1.775626e+18,XekiHlongwane,2013-09-20 12:21:01+00:00,qme,1.0,"Place(id='dd9c0d7d7e07eb49', fullName='South A...",NaN,üìç Architecture ‚úçüèæ,...,False,True,NaN,ae3ba8e8,1775624995265302531,3,4:1,mancity,avfcofficial,NaN
1622,2024-04-03 20:42:31+00:00,@ManCity @PhilFoden Let‚Äôs score more goals to ...,1.775625e+18,XekiHlongwane,2013-09-20 12:21:01+00:00,en,2.0,"Place(id='dd9c0d7d7e07eb49', fullName='South A...",NaN,üìç Architecture ‚úçüèæ,...,False,True,NaN,ae3ba8e8,1775624453013020917,3,4:1,mancity,avfcofficial,NaN
2738,2024-02-05 20:27:40+00:00,@ManCity Soon it will be KDBüòç https://t.co/vbX...,1.754603e+18,XekiHlongwane,2013-09-20 12:21:01+00:00,en,4.0,"Place(id='dd9c0d7d7e07eb49', fullName='South A...",NaN,üìç Architecture ‚úçüèæ,...,False,True,NaN,2b3630b6,1754601150320431451,1,1:2,brentfordfc,mancity,NaN
2885,2024-01-31 19:54:59+00:00,@ManCity Great combination üòç https://t.co/Wob6...,1.752783e+18,XekiHlongwane,2013-09-20 12:21:01+00:00,en,0.0,"Place(id='dd9c0d7d7e07eb49', fullName='South A...",NaN,üìç Architecture ‚úçüèæ,...,False,True,NaN,d10aaae8,1752782033271583051,3,3:0,mancity,burnleyofficial,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77990,2023-12-02 15:28:00+00:00,@SheffieldUnited Looks like a safe substitutio...,1.730972e+18,TravelChannel69,2023-06-26 03:10:12+00:00,en,1.0,"Place(id='0192af60292eace8', fullName='Hanoi, ...",NaN,"H√† N·ªôi, Vi·ªát Nam",...,False,False,NaN,e2c53b0a,1730971962652938265,-2,2:0,burnleyofficial,sheffieldunited,NaN
77995,2023-12-02 15:20:52+00:00,@SheffieldUnited Looks like Norwood is warming...,1.730970e+18,TravelChannel69,2023-06-26 03:10:12+00:00,en,4.0,"Place(id='0192af60292eace8', fullName='Hanoi, ...",NaN,"H√† N·ªôi, Vi·ªát Nam",...,False,False,NaN,e2c53b0a,1730970159123202335,-2,2:0,burnleyofficial,sheffieldunited,NaN
78003,2023-12-02 15:05:34+00:00,"@SheffieldUnited On the bright side, plenty of...",1.730966e+18,TravelChannel69,2023-06-26 03:10:12+00:00,en,26.0,"Place(id='0192af60292eace8', fullName='Hanoi, ...",NaN,"H√† N·ªôi, Vi·ªát Nam",...,False,False,NaN,e2c53b0a,1730966288342655485,-2,2:0,burnleyofficial,sheffieldunited,NaN
78300,2023-10-28 15:18:03+00:00,@SheffieldUnited Simply not good enough. Can‚Äôt...,1.718286e+18,140Shore,2014-12-10 19:59:49+00:00,en,1.0,"Place(id='4efd6fc8c50fae33', fullName='Yorkshi...",NaN,NaN,...,False,False,NaN,d498f918,1718285535624499563,-3,3:0,arsenal,sheffieldunited,NaN
78810,2023-09-24 16:16:43+00:00,@SheffieldUnited https://t.co/H1OsjIlbPw,1.705980e+18,patrickpops,2011-01-16 22:37:58+00:00,qme,3.0,"Place(id='208d28e57bdc12e9', fullName='Wales, ...",NaN,"Wrecsam, Cymru üè¥Û†ÅßÛ†Å¢Û†Å∑Û†Å¨Û†Å≥Û†Åø",...,False,False,NaN,cf4fef85,1705976772238454811,-2,0:2,sheffieldunited,nufc,NaN

In [171]:
no_country[~no_country["place"].isna()]["place"].unique()

array(["Place(id='000763a81141ab85', fullName='Maiduguri, Nigeria', name='Maiduguri', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='dd9c0d7d7e07eb49', fullName='South Africa', name='South Africa', type='country', country='South Africa', countryCode='ZA')",
       "Place(id='685cfffb7890af3e', fullName='Startforth, England', name='Startforth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='1465fdb4074020c2', fullName='Germiston, South Africa', name='Germiston', type='city', country='South Africa', countryCode='ZA')",
       "Place(id='001907e868d06e24', fullName='Dubai, United Arab Emirates', name='Dubai', type='admin', country='United Arab Emirates', countryCode='AE')",
       "Place(id='537b8c5518197832', fullName='Enfield, London', name='Enfield', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='014d44840ab94333', fullName='Luwero, Uganda', name='Luwero', type='admin', country='Uganda', countryCode='UG')",
       "Place(id='3797791ff9c0e4c6', fullName='Toronto, Ontario', name='Toronto', type='city', country='Canada', countryCode='CA')",
       "Place(id='42565705ca677b94', fullName='Medan Denai, Indonesia', name='Medan Denai', type='city', country='Indonesia', countryCode='ID')",
       "Place(id='018f1cde6bad9747', fullName='Ciudad Aut√≥noma de Buenos Aires, Argentina', name='Ciudad Aut√≥noma de Buenos Aires', type='city', country='Argentina', countryCode='AR')",
       "Place(id='60160252aeb7e3e5', fullName='West Midlands, England', name='West Midlands', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='24375e528db392ff', fullName='Innisfil, Ontario', name='Innisfil', type='city', country='Canada', countryCode='CA')",
       "Place(id='73a5d83329504007', fullName='Fingal, Ireland', name='Fingal', type='city', country='Ireland', countryCode='IE')",
       "Place(id='01eddd9d0dbec2c8', fullName='Ikeja, Nigeria', name='Ikeja', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='513372d74ee7530b', fullName='Ayr, Scotland', name='Ayr', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='00c39537733fa112', fullName='Queens, NY', name='Queens', type='city', country='United States', countryCode='US')",
       "Place(id='01d904b74c275f34', fullName='Imo, Nigeria', name='Imo', type='admin', country='Nigeria', countryCode='NG')",
       "Place(id='ac9b9070f6d17a9a', fullName='Nebraska, USA', name='Nebraska', type='admin', country='United States', countryCode='US')",
       "Place(id='000799c66e428a87', fullName='Jeddah, Kingdom of Saudi Arabia', name='Jeddah', type='city', country='Kingdom of Saudi Arabia', countryCode='SA')",
       "Place(id='1f3d386c66451137', fullName='Hartlepool, England', name='Hartlepool', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='67bc7263f7b9047b', fullName='North East, England', name='North East', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='100b272c02934631', fullName='Gateshead, England', name='Gateshead', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='e59069aafae0aa25', fullName='South Dublin, Ireland', name='South Dublin', type='city', country='Ireland', countryCode='IE')",
       "Place(id='23b629b33fba1676', fullName='Qu√©bec, Canada', name='Qu√©bec', type='city', country='Canada', countryCode='CA')",
       "Place(id='3f9943ff6abe6a32', fullName='Denecrest, England', name='Denecrest', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='78e9729ff12a648e', fullName='Northern Ireland, United Kingdom', name='Northern Ireland', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='01065a114b362889', fullName='Rift Valley, Kenya', name='Rift Valley', type='admin', country='Kenya', countryCode='KE')",
       "Place(id='071b6687ed6a34e3', fullName='Heybridge, East', name='Heybridge', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='0136dbe81e7f723c', fullName='Ekpoma, Nigeria', name='Ekpoma', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='003d5766281b4194', fullName='Lahore, Pakistan', name='Lahore', type='city', country='Pakistan', countryCode='PK')",
       "Place(id='5f73d127c7ccf9d9', fullName='Croydon, London', name='Croydon', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='23d81de6fe7594cb', fullName='Goi√¢nia, Brazil', name='Goi√¢nia', type='city', country='Brazil', countryCode='BR')",
       "Place(id='00f24ae701a1207b', fullName='Abu Dhabi, United Arab Emirates', name='Abu Dhabi', type='admin', country='United Arab Emirates', countryCode='AE')",
       "Place(id='0de2b96e52986b41', fullName='Sompting, England', name='Sompting', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='d9d978b087a92583', fullName='Belo Horizonte, Brazil', name='Belo Horizonte', type='city', country='Brazil', countryCode='BR')",
       "Place(id='6c3784993a540a38', fullName='Harlow, East', name='Harlow', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='1c3680c48401e703', fullName='Staines-upon-Thames, South East', name='Staines-upon-Thames', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='5568fcf97199b753', fullName='Luton, England', name='Luton', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='4f854c83732cf4f5', fullName='Watford, East', name='Watford', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='d6539f049c4d05e8', fullName='Lowell, MA', name='Lowell', type='city', country='United States', countryCode='US')",
       "Place(id='09ba692cbddfc92c', fullName='Hammersmith, London', name='Hammersmith', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='5a110d312052166f', fullName='San Francisco, CA', name='San Francisco', type='city', country='United States', countryCode='US')",
       "Place(id='7dde0febc9ef245b', fullName='Dublin City, Ireland', name='Dublin City', type='city', country='Ireland', countryCode='IE')",
       "Place(id='0cbfb5dccb8131b8', fullName='North West, England', name='North West', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='151b9e91272233d1', fullName='Liverpool, England', name='Liverpool', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='16a7928fc7d1075a', fullName='Warrington, England', name='Warrington', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='1b88a6ba7f333607', fullName='Alexandra, South Africa', name='Alexandra', type='city', country='South Africa', countryCode='ZA')",
       "Place(id='426f6a3e00c879a4', fullName='GrudziƒÖdz, Polska', name='GrudziƒÖdz', type='city', country='Poland', countryCode='PL')",
       "Place(id='85c09b7b6a803faf', fullName='Southglenn, CO', name='Southglenn', type='city', country='United States', countryCode='US')",
       "Place(id='0192af60292eace8', fullName='Hanoi, Vietnam', name='Hanoi', type='admin', country='Vietnam', countryCode='VN')",
       "Place(id='8c86b8b4cb716103', fullName='Seville, Spain', name='Seville', type='city', country='Spain', countryCode='ES')",
       "Place(id='54d258d7002e5735', fullName='Potten End, England', name='Potten End', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='015885060e250430', fullName='Matabeleland South, Zimbabwe', name='Matabeleland South', type='admin', country='Zimbabwe', countryCode='ZW')",
       "Place(id='59efa64f5c8f5340', fullName='Grahamstown, South Africa', name='Grahamstown', type='city', country='South Africa', countryCode='ZA')",
       "Place(id='07e9c7d1954fff64', fullName='Sheffield, England', name='Sheffield', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='4efd6fc8c50fae33', fullName='Yorkshire and The Humber, England', name='Yorkshire and The Humber', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='01973562619fa93b', fullName='Tom√©, Chile', name='Tom√©', type='city', country='Chile', countryCode='CL')",
       "Place(id='00e5748317406e5e', fullName='Vƒ©nh Ph√∫c, Vietnam', name='Vƒ©nh Ph√∫c', type='admin', country='Vietnam', countryCode='VN')",
       "Place(id='208d28e57bdc12e9', fullName='Wales, United Kingdom', name='Wales', type='admin', country='United Kingdom', countryCode='GB')"],
      dtype=object)

In [172]:
np.unique([v for v in mapping.values()])

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Angola',
       'Antarctica', 'Argentina', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Benin',
       'Bermuda', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada',
       'Chile', 'China', 'Colombia', 'Congo (DRC)', 'Congo - Kinshasa',
       'Costa Rica', 'Croatia', 'Cuba', 'Cura√ßao', 'Cyprus',
       'Czech Republic', 'Czechia', 'Democratic Republic of the Congo',
       'Denmark', 'Earth', 'Ecuador', 'Egypt', 'England', 'Estonia',
       'Ethiopia', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy',
       'Ivory Coast', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kenya',
       'Korea', 'Kosovo', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi',
       'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'M√©xico', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'None',
       'North Korea', 'Northern Ireland', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Palestinian Territories', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Taiwan', 'Tanzania',
       'Thailand', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'T√ºrkiye',
       'UAE', 'UK', 'USA', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Viet Nam',
       'Vietnam', 'Wales', 'Zambia', 'Zimbabwe', 'eSwatini', 'ÿßŸÑÿπÿ±ÿ®Ÿäÿ©'],
      dtype='<U32')

In [173]:
# further generalize some of the locations
replies.loc[replies['user_country'] == "T√ºrkiye", 'user_country'] = "Turkey"
replies.loc[replies['user_country'].isin(["Congo (DRC)", "Congo - Kinshasa"]), 'user_country'] = "Democratic Republic of the Congo"
replies.loc[replies['user_country'] == "Czechia", 'user_country'] = "Czech Republic"
replies.loc[replies['user_country'] == "Korea", 'user_country'] = "South Korea"
replies.loc[replies['user_country'] == "UAE", 'user_country'] = "United Arab Emirates"
replies.loc[replies['user_country'] == "Viet Nam", 'user_country'] = "Vietnam"
replies.loc[replies['user_country'] == "UK", 'user_country'] = "United Kingdom"

In [174]:
replies["user_country"].unique()

array(['England', nan, 'None', 'United Kingdom', 'Nigeria',
       'Saudi Arabia', 'South Africa', 'USA', 'Turkey',
       'United Arab Emirates', 'Poland', 'Netherlands', 'India',
       'Australia', 'Canada', 'Spain', 'Kenya', 'Pakistan', 'Uganda',
       'Jamaica', 'Luxembourg', 'Tanzania', 'Malaysia', 'France',
       'Morocco', 'China', 'Kuwait', 'Brazil', 'Germany', 'Ireland',
       'Ghana', 'Vietnam', 'Qatar', 'Chile', 'Croatia', 'Denmark',
       'Angola', 'Bangladesh', 'Belgium', 'Mexico', 'Cyprus', 'Venezuela',
       'New Zealand', 'Scotland', 'Somalia', 'Austria', 'Israel',
       'Indonesia', 'Botswana', 'Cura√ßao', 'Bahrain', 'Finland',
       'Colombia', 'Argentina', 'Iceland', 'Greece', 'South Korea',
       'Norway', 'Czech Republic', 'Honduras', 'Mozambique', 'Zimbabwe',
       'Ecuador', 'Switzerland', 'Egypt', 'Japan', 'Northern Ireland',
       'Wales', 'Mauritania', 'Georgia', 'Sweden', 'Peru', 'Albania',
       'Afghanistan', 'Africa', 'Italy', 'Slovenia', 'Serbia', 'Oman',
       'Singapore', 'Gambia', 'Thailand', 'Zambia', 'Namibia', 'Senegal',
       'Monaco', 'Portugal', 'Montenegro', 'Romania', 'Iraq', 'Hungary',
       'Taiwan', 'Costa Rica', 'Bahamas', 'Mauritius', 'Azerbaijan',
       'Hong Kong', 'Democratic Republic of the Congo', 'Jersey',
       'Bulgaria', 'eSwatini', 'Malta', 'Russia', 'Ivory Coast', 'Sudan',
       'Seychelles', 'Puerto Rico', 'South Sudan', 'Papua New Guinea',
       'Cuba', 'Paraguay', 'Rwanda', 'Madagascar', 'Palestine',
       'Mongolia', 'Ethiopia', 'Earth', 'Cameroon', 'Ukraine', 'Algeria',
       'Nicaragua', 'Antarctica', 'Liberia', 'Estonia', 'Guatemala',
       'Macedonia', 'Sierra Leone', 'Benin', 'Lesotho', 'Suriname',
       'Tunisia', 'Philippines', 'Libya', 'Lebanon', 'Uzbekistan',
       'Bermuda', 'Malawi', 'M√©xico', 'Slovakia', 'Nepal', 'Myanmar',
       'Fiji', 'Uruguay', 'Panama', 'Falkland Islands', 'Isle of Man',
       'North Korea', 'Belarus', 'Trinidad and Tobago', 'Niger', 'Mali',
       'Kosovo', 'Burundi', 'Bosnia and Herzegovina'], dtype=object)

In [175]:
# probs gonna delete these
replies[replies["user_country"] == "North Korea"]["user_location"]

67463    North Korea
69052    North Korea
69344     Pyongyang
69371     Pyongyang
72149     Pyongyang
75644    North Korea
75898    North Korea
Name: user_location, dtype: object

In [176]:
replies[replies["user_country"] == "Palestinian Territories"]#["user_location"]

Empty DataFrame
Columns: [datetime, tweet, id, user_handle, created, lang, likes, place, coords, user_location, user_description, user_followers, user_verified, user_blue, user_blue_type, report_id, parent_tweet_id, margin, score, home_team, away_team, user_country]
Index: []

[0 rows x 22 columns]

In [177]:
country_counts = replies['user_country'].value_counts()
country_counts

user_country
England           14407
None              12345
Nigeria            4819
USA                4499
United Kingdom     1125
                  ...
Macedonia             1
Guatemala             1
Cameroon              1
Liberia               1
Seychelles            1
Name: count, Length: 153, dtype: int64

In [178]:
unique_user_counts = replies.groupby('user_country')['user_handle'].nunique()

country_users = pd.DataFrame({
    'count': country_counts,
    'unique_users': unique_user_counts
})

In [179]:
country_users.sort_values(by=["count", "unique_users"], ascending=False)

                     count  unique_users
user_country
England              14407          4386
None                 12345          2257
Nigeria               4819           808
USA                   4499          1133
United Kingdom        1125           323
...                    ...           ...
Seychelles               1             1
Slovakia                 1             1
South Sudan              1             1
Trinidad and Tobago      1             1
eSwatini                 1             1

[153 rows x 2 columns]

In [180]:
# mapping places to countries
# if place and user_location both exist, the country that place is mapped to overrides that of user_location
places = replies["place"].unique()

In [181]:
re.search(r"fullName='(.*?)'", places[1]).group(1)

'Maiduguri, Nigeria'

In [182]:
[re.search(r"fullName='(.*?)'", place).group(1) for place in places[1:]]

['Maiduguri, Nigeria',
 'Germiston, South Africa',
 'South Africa',
 'Dar es Salaam, Tanzania',
 'Accra, Ghana',
 'Kampala, Uganda',
 'Punjab, Pakistan',
 'Startforth, England',
 'Camberwell, London',
 'Rijiyar Zaki, Nigeria',
 'Manchester, England',
 'Dubai, United Arab Emirates',
 'Washington, DC',
 'Enfield, London',
 'South East, England',
 'Kumasi, Ghana',
 'East, England',
 'Walkden, England',
 'Bahrain',
 'Nairobi, Kenya',
 'Luwero, Uganda',
 'Toronto, Ontario',
 'Port Harcourt, Nigeria',
 'Northampton, England',
 'ƒ∞stanbul, T√ºrkiye',
 'Warrington, England',
 'Thunder Bay, Ontario',
 'Medan Denai, Indonesia',
 'Wales, England',
 'Evesham, England',
 'Ciudad Aut√≥noma de Buenos Aires, Argentina',
 'Braga, Portugal',
 'Birmingham, England',
 'West Midlands, England',
 'Plymouth, England',
 'Witney, England',
 'Tampere, Finland',
 'Hig√ºey, Dominican Republic',
 'Carlton, England',
 'Benito Ju√°rez, Quintana Roo',
 'South Dublin, Ireland',
 'Polesworth, England',
 'Innisfil, Ontario',
 'Kingswood, England',
 'Fingal, Ireland',
 'Islington, London',
 'Ikeja, Nigeria',
 'Iseyin, Nigeria',
 'Paradise, NV',
 'Ayr, Scotland',
 'Queens, NY',
 'London, England',
 'Lagos, Nigeria',
 'Mongolia',
 'Clacton-on-Sea, England',
 'Lagos, Nigeria',
 'Belfast, Northern Ireland',
 'Aguachica, Colombia',
 'Warsaw, Poland',
 'Imo, Nigeria',
 'East Orange, NJ',
 'Oyarifa, Ghana',
 'Nea Alikarnassos, Greece',
 'Kisumu, Kenya',
 'Arkadi, Greece',
 'Nebraska, USA',
 'Rotterdam, The Netherlands',
 'Ilorin, Nigeria',
 'North West, England',
 'West Bromwich, England',
 'Jeddah, Kingdom of Saudi Arabia',
 'Islamabad, Pakistan',
 'Blyth, England',
 'Hartlepool, England',
 'Sydney, New South Wales',
 'Merrimack, NH',
 'North East, England',
 'Gateshead, England',
 'Coningsby, England',
 'Qu√©bec, Canada',
 'Denecrest, England',
 'High Beech, East',
 'East Kilbride, Scotland',
 'Aziziah, Kingdom of Saudi Arabia',
 'New Jersey, USA',
 'Kakuma, Kenya',
 'Dammam, Kingdom of Saudi Arabia',
 'West Covina, CA',
 'Northern Ireland, United Kingdom',
 'Al Khobar, Kingdom of Saudi Arabia',
 'Federal Capital Territory, Nigeria',
 'Houston, TX',
 'Bor√•s, Sverige',
 'Rift Valley, Kenya',
 'Heybridge, East',
 'Stafford, England',
 'Milton Keynes, England',
 'Valley Stream, NY',
 'San Antonio, TX',
 'Windcrest, TX',
 'Canberra, Australian Capital Territory',
 'Ekpoma, Nigeria',
 'Lahore, Pakistan',
 'Wales, United Kingdom',
 'Croydon, London',
 'Pollen√ßa, Spain',
 'Rochester, South East',
 'Gatineau, Qu√©bec',
 'Goi√¢nia, Brazil',
 'Abu Dhabi, United Arab Emirates',
 'England, United Kingdom',
 'Louisville, KY',
 'Banstead, South East',
 'Kano, Nigeria',
 'Barnet, London',
 'Samaru, Nigeria',
 'Massachusetts, USA',
 'Sompting, England',
 'Benin-City, Nigeria',
 'Belo Horizonte, Brazil',
 'Kiama, New South Wales',
 'Port Hadlock-Irondale, WA',
 'Bournemouth, England',
 'Poole, England',
 'Kensington, London',
 'South West, England',
 'Upton, England',
 'Anduze, France',
 'Harlow, East',
 'Melbourne, Victoria',
 'Staines-upon-Thames, South East',
 'Luton, England',
 'Ashington, England',
 'Brong-Ahafo, Ghana',
 'Denver, CO',
 'Albania',
 'Watford, East',
 'Lowell, MA',
 'Hammersmith, London',
 'East Midlands, England',
 'Florida, USA',
 'Cileungsi, Indonesia',
 'Wandsworth, London',
 'San Francisco, CA',
 'Wolverhampton, England',
 'Baltimore, MD',
 'Rio de Janeiro, Brazil',
 'Albuquerque, NM',
 'Dudley, England',
 'Wednesfield, England',
 'Cibinong, Indonesia',
 'Dublin City, Ireland',
 'Heswall, England',
 'Thika, Kenya',
 'Liverpool, England',
 'Alexandra, South Africa',
 'Maghull, England',
 'Margate, England',
 'Hackney, London',
 'Las Cruces, NM',
 'Ghent, Belgium',
 'Warri, Nigeria',
 'GrudziƒÖdz, Polska',
 'Newbury, England',
 'Nolensville, TN',
 'Broadstairs, England',
 'Lexington, SC',
 'Southglenn, CO',
 'Hanoi, Vietnam',
 'Hounslow, London',
 'Eltham, London',
 'Los Angeles, CA',
 'Washington, USA',
 'Nashville, TN',
 'St Michael, MN',
 'Bristol, England',
 'Mansfield, England',
 'Nottingham, England',
 'Hambrook, England',
 'Senegal',
 'Mitcheldean, England',
 'Meath, Ireland',
 'Seville, Spain',
 'Kaduna, Nigeria',
 'Hertford, East',
 'Southend-on-Sea, East',
 'Potten End, England',
 'Matabeleland South, Zimbabwe',
 'Urmston, England',
 'Pretoria, South Africa',
 'Milnerton, South Africa',
 'Grahamstown, South Africa',
 'Colne, England',
 'Burnley, England',
 'Centurion, South Africa',
 'Espoo, Suomi',
 'Glenrothes, Scotland',
 'Sheffield, England',
 'Yorkshire and The Humber, England',
 'Gillingham, England',
 'Rayleigh, East',
 'Bradford, England',
 'Tom√©, Chile',
 'Brent, London',
 'Vƒ©nh Ph√∫c, Vietnam',
 'Tottenham, London',
 'Cork, Ireland']

In [183]:
places

array([nan,
       "Place(id='000763a81141ab85', fullName='Maiduguri, Nigeria', name='Maiduguri', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='1465fdb4074020c2', fullName='Germiston, South Africa', name='Germiston', type='city', country='South Africa', countryCode='ZA')",
       "Place(id='dd9c0d7d7e07eb49', fullName='South Africa', name='South Africa', type='country', country='South Africa', countryCode='ZA')",
       "Place(id='00d9827647c0ff5a', fullName='Dar es Salaam, Tanzania', name='Dar es Salaam', type='admin', country='Tanzania', countryCode='TZ')",
       "Place(id='003e299707d0375b', fullName='Accra, Ghana', name='Accra', type='city', country='Ghana', countryCode='GH')",
       "Place(id='000c69ad123213a8', fullName='Kampala, Uganda', name='Kampala', type='admin', country='Uganda', countryCode='UG')",
       "Place(id='00cc0d5640394308', fullName='Punjab, Pakistan', name='Punjab', type='admin', country='Pakistan', countryCode='PK')",
       "Place(id='685cfffb7890af3e', fullName='Startforth, England', name='Startforth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='7f55e839e1715da2', fullName='Camberwell, London', name='Camberwell', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='001036c439d2e6b6', fullName='Rijiyar Zaki, Nigeria', name='Rijiyar Zaki', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='315b740b108481f6', fullName='Manchester, England', name='Manchester', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='001907e868d06e24', fullName='Dubai, United Arab Emirates', name='Dubai', type='admin', country='United Arab Emirates', countryCode='AE')",
       "Place(id='01fbe706f872cb32', fullName='Washington, DC', name='Washington', type='city', country='United States', countryCode='US')",
       "Place(id='537b8c5518197832', fullName='Enfield, London', name='Enfield', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='06168d1feda43857', fullName='South East, England', name='South East', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='009b4bcc18019797', fullName='Kumasi, Ghana', name='Kumasi', type='city', country='Ghana', countryCode='GH')",
       "Place(id='3bc1b6cfd27ef7f6', fullName='East, England', name='East', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='218e2768b9210c6c', fullName='Walkden, England', name='Walkden', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='e3e9c55876b99760', fullName='Bahrain', name='Bahrain', type='country', country='Bahrain', countryCode='BH')",
       "Place(id='01e215db7136a37e', fullName='Nairobi, Kenya', name='Nairobi', type='city', country='Kenya', countryCode='KE')",
       "Place(id='014d44840ab94333', fullName='Luwero, Uganda', name='Luwero', type='admin', country='Uganda', countryCode='UG')",
       "Place(id='3797791ff9c0e4c6', fullName='Toronto, Ontario', name='Toronto', type='city', country='Canada', countryCode='CA')",
       "Place(id='0008cb6457ff0b55', fullName='Port Harcourt, Nigeria', name='Port Harcourt', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='28b6432fb1eac6d4', fullName='Northampton, England', name='Northampton', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='5e02a0f0d91c76d2', fullName='ƒ∞stanbul, T√ºrkiye', name='ƒ∞stanbul', type='city', country='Turkey', countryCode='TR')",
       "Place(id='16a7928fc7d1075a', fullName='Warrington, England', name='Warrington', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='4f0206a4181479ef', fullName='Thunder Bay, Ontario', name='Thunder Bay', type='city', country='Canada', countryCode='CA')",
       "Place(id='42565705ca677b94', fullName='Medan Denai, Indonesia', name='Medan Denai', type='city', country='Indonesia', countryCode='ID')",
       "Place(id='732e1664fe9a12e3', fullName='Wales, England', name='Wales', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='611cf272424ab617', fullName='Evesham, England', name='Evesham', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='018f1cde6bad9747', fullName='Ciudad Aut√≥noma de Buenos Aires, Argentina', name='Ciudad Aut√≥noma de Buenos Aires', type='city', country='Argentina', countryCode='AR')",
       "Place(id='5b12348ecc3f2565', fullName='Braga, Portugal', name='Braga', type='city', country='Portugal', countryCode='PT')",
       "Place(id='53b67b1d1cc81a51', fullName='Birmingham, England', name='Birmingham', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='60160252aeb7e3e5', fullName='West Midlands, England', name='West Midlands', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='7aeb72d9e8a1c889', fullName='Plymouth, England', name='Plymouth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='666a4c66682d5ce7', fullName='Witney, England', name='Witney', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='e3ba9e096a0fc232', fullName='Tampere, Finland', name='Tampere', type='city', country='Finland', countryCode='FI')",
       "Place(id='0103d4375c78ffad', fullName='Hig√ºey, Dominican Republic', name='Hig√ºey', type='city', country='Dominican Republic', countryCode='DO')",
       "Place(id='4e5d1e9bc3c752b2', fullName='Carlton, England', name='Carlton', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='6eb95eddb81a6b4b', fullName='Benito Ju√°rez, Quintana Roo', name='Benito Ju√°rez', type='city', country='Mexico', countryCode='MX')",
       "Place(id='e59069aafae0aa25', fullName='South Dublin, Ireland', name='South Dublin', type='city', country='Ireland', countryCode='IE')",
       "Place(id='68bd352a83089f8b', fullName='Polesworth, England', name='Polesworth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='24375e528db392ff', fullName='Innisfil, Ontario', name='Innisfil', type='city', country='Canada', countryCode='CA')",
       "Place(id='52e6f17df9e90c0a', fullName='Kingswood, England', name='Kingswood', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='73a5d83329504007', fullName='Fingal, Ireland', name='Fingal', type='city', country='Ireland', countryCode='IE')",
       "Place(id='544762ebf7fda780', fullName='Islington, London', name='Islington', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='01eddd9d0dbec2c8', fullName='Ikeja, Nigeria', name='Ikeja', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='0132f8fe4226cc30', fullName='Iseyin, Nigeria', name='Iseyin', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='8fa6d7a33b83ef26', fullName='Paradise, NV', name='Paradise', type='city', country='United States', countryCode='US')",
       "Place(id='513372d74ee7530b', fullName='Ayr, Scotland', name='Ayr', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='00c39537733fa112', fullName='Queens, NY', name='Queens', type='city', country='United States', countryCode='US')",
       "Place(id='5d838f7a011f4a2d', fullName='London, England', name='London', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='00817d75276a95cf', fullName='Lagos, Nigeria', name='Lagos', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='8bd61930ae4f642d', fullName='Mongolia', name='Mongolia', type='country', country='Mongolia', countryCode='MN')",
       "Place(id='0c938e54810a6d61', fullName='Clacton-on-Sea, England', name='Clacton-on-Sea', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='011a942e0a0e8fb2', fullName='Lagos, Nigeria', name='Lagos', type='admin', country='Nigeria', countryCode='NG')",
       "Place(id='28679b23ed15b380', fullName='Belfast, Northern Ireland', name='Belfast', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='005594b458d3d648', fullName='Aguachica, Colombia', name='Aguachica', type='city', country='Colombia', countryCode='CO')",
       "Place(id='535f0c2de0121451', fullName='Warsaw, Poland', name='Warsaw', type='city', country='Poland', countryCode='PL')",
       "Place(id='01d904b74c275f34', fullName='Imo, Nigeria', name='Imo', type='admin', country='Nigeria', countryCode='NG')",
       "Place(id='858cec499f8adba6', fullName='East Orange, NJ', name='East Orange', type='city', country='United States', countryCode='US')",
       "Place(id='0085c4a6640325a8', fullName='Oyarifa, Ghana', name='Oyarifa', type='city', country='Ghana', countryCode='GH')",
       "Place(id='01cb1a894c5b0cb2', fullName='Nea Alikarnassos, Greece', name='Nea Alikarnassos', type='city', country='Greece', countryCode='GR')",
       "Place(id='010440c10c428c7a', fullName='Kisumu, Kenya', name='Kisumu', type='city', country='Kenya', countryCode='KE')",
       "Place(id='00d540a67baf80a3', fullName='Arkadi, Greece', name='Arkadi', type='city', country='Greece', countryCode='GR')",
       "Place(id='ac9b9070f6d17a9a', fullName='Nebraska, USA', name='Nebraska', type='admin', country='United States', countryCode='US')",
       "Place(id='ea0a61fa0c646676', fullName='Rotterdam, The Netherlands', name='Rotterdam', type='city', country='The Netherlands', countryCode='NL')",
       "Place(id='01cba65c41c20b24', fullName='Ilorin, Nigeria', name='Ilorin', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='0cbfb5dccb8131b8', fullName='North West, England', name='North West', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='6bc1630ac15fbcaa', fullName='West Bromwich, England', name='West Bromwich', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='000799c66e428a87', fullName='Jeddah, Kingdom of Saudi Arabia', name='Jeddah', type='city', country='Kingdom of Saudi Arabia', countryCode='SA')",
       "Place(id='00685eca27fbd26b', fullName='Islamabad, Pakistan', name='Islamabad', type='city', country='Pakistan', countryCode='PK')",
       "Place(id='2d284af2398c0eb9', fullName='Blyth, England', name='Blyth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='1f3d386c66451137', fullName='Hartlepool, England', name='Hartlepool', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='0073b76548e5984f', fullName='Sydney, New South Wales', name='Sydney', type='city', country='Australia', countryCode='AU')",
       "Place(id='000a400a1aba18e8', fullName='Merrimack, NH', name='Merrimack', type='city', country='United States', countryCode='US')",
       "Place(id='67bc7263f7b9047b', fullName='North East, England', name='North East', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='100b272c02934631', fullName='Gateshead, England', name='Gateshead', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='17fdc0a30e401236', fullName='Coningsby, England', name='Coningsby', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='23b629b33fba1676', fullName='Qu√©bec, Canada', name='Qu√©bec', type='city', country='Canada', countryCode='CA')",
       "Place(id='3f9943ff6abe6a32', fullName='Denecrest, England', name='Denecrest', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='7166735baf0c75fa', fullName='High Beech, East', name='High Beech', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='38eabeb176f29378', fullName='East Kilbride, Scotland', name='East Kilbride', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='00b374d34e8d3ac1', fullName='Aziziah, Kingdom of Saudi Arabia', name='Aziziah', type='city', country='Kingdom of Saudi Arabia', countryCode='SA')",
       "Place(id='65b4760a2b411e11', fullName='New Jersey, USA', name='New Jersey', type='admin', country='United States', countryCode='US')",
       "Place(id='00f565ea19a64b48', fullName='Kakuma, Kenya', name='Kakuma', type='city', country='Kenya', countryCode='KE')",
       "Place(id='01af894d0e430d75', fullName='Dammam, Kingdom of Saudi Arabia', name='Dammam', type='city', country='Kingdom of Saudi Arabia', countryCode='SA')",
       "Place(id='1193edda55d6fa3d', fullName='West Covina, CA', name='West Covina', type='city', country='United States', countryCode='US')",
       "Place(id='78e9729ff12a648e', fullName='Northern Ireland, United Kingdom', name='Northern Ireland', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='01b9bce9425c3081', fullName='Al Khobar, Kingdom of Saudi Arabia', name='Al Khobar', type='city', country='Kingdom of Saudi Arabia', countryCode='SA')",
       "Place(id='01c46739344ba9f6', fullName='Federal Capital Territory, Nigeria', name='Federal Capital Territory', type='admin', country='Nigeria', countryCode='NG')",
       "Place(id='1c69a67ad480e1b1', fullName='Houston, TX', name='Houston', type='city', country='United States', countryCode='US')",
       "Place(id='c238ebe8b6909ac1', fullName='Bor√•s, Sverige', name='Bor√•s', type='city', country='Sweden', countryCode='SE')",
       "Place(id='01065a114b362889', fullName='Rift Valley, Kenya', name='Rift Valley', type='admin', country='Kenya', countryCode='KE')",
       "Place(id='071b6687ed6a34e3', fullName='Heybridge, East', name='Heybridge', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='167350ace62962b7', fullName='Stafford, England', name='Stafford', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='17cc57fae415c45e', fullName='Milton Keynes, England', name='Milton Keynes', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='a6bb3ed9f8ccb4a2', fullName='Valley Stream, NY', name='Valley Stream', type='city', country='United States', countryCode='US')",
       "Place(id='3df4f427b5a60fea', fullName='San Antonio, TX', name='San Antonio', type='city', country='United States', countryCode='US')",
       "Place(id='841581268d9f2f86', fullName='Windcrest, TX', name='Windcrest', type='city', country='United States', countryCode='US')",
       "Place(id='01e4b0c84959d430', fullName='Canberra, Australian Capital Territory', name='Canberra', type='city', country='Australia', countryCode='AU')",
       "Place(id='0136dbe81e7f723c', fullName='Ekpoma, Nigeria', name='Ekpoma', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='003d5766281b4194', fullName='Lahore, Pakistan', name='Lahore', type='city', country='Pakistan', countryCode='PK')",
       "Place(id='208d28e57bdc12e9', fullName='Wales, United Kingdom', name='Wales', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='5f73d127c7ccf9d9', fullName='Croydon, London', name='Croydon', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='44a5545331e3af09', fullName='Pollen√ßa, Spain', name='Pollen√ßa', type='city', country='Spain', countryCode='ES')",
       "Place(id='0292257d85023f3f', fullName='Rochester, South East', name='Rochester', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='127021a2772dbff7', fullName='Gatineau, Qu√©bec', name='Gatineau', type='city', country='Canada', countryCode='CA')",
       "Place(id='23d81de6fe7594cb', fullName='Goi√¢nia, Brazil', name='Goi√¢nia', type='city', country='Brazil', countryCode='BR')",
       "Place(id='00f24ae701a1207b', fullName='Abu Dhabi, United Arab Emirates', name='Abu Dhabi', type='admin', country='United Arab Emirates', countryCode='AE')",
       "Place(id='8ef32ff56ef11c22', fullName='England, United Kingdom', name='England', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='095534ad3107e0e6', fullName='Louisville, KY', name='Louisville', type='city', country='United States', countryCode='US')",
       "Place(id='1bfd34ea190a59c2', fullName='Banstead, South East', name='Banstead', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='00611f1548c7bdef', fullName='Kano, Nigeria', name='Kano', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='7ef79c5ab17d518c', fullName='Barnet, London', name='Barnet', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='01582c07092232af', fullName='Samaru, Nigeria', name='Samaru', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='cd450c94084cbf9b', fullName='Massachusetts, USA', name='Massachusetts', type='admin', country='United States', countryCode='US')",
       "Place(id='0de2b96e52986b41', fullName='Sompting, England', name='Sompting', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='005dbe7e6949db42', fullName='Benin-City, Nigeria', name='Benin-City', type='city', country='Nigeria', countryCode='NG')",
       "Place(id='d9d978b087a92583', fullName='Belo Horizonte, Brazil', name='Belo Horizonte', type='city', country='Brazil', countryCode='BR')",
       "Place(id='01970de32eabe474', fullName='Kiama, New South Wales', name='Kiama', type='city', country='Australia', countryCode='AU')",
       "Place(id='0dd5d0d954d5b20e', fullName='Port Hadlock-Irondale, WA', name='Port Hadlock-Irondale', type='city', country='United States', countryCode='US')",
       "Place(id='7de31e05e99a00f8', fullName='Bournemouth, England', name='Bournemouth', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='1c4cd8e4ae3a1959', fullName='Poole, England', name='Poole', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='01c7ed8caf11e8b2', fullName='Kensington, London', name='Kensington', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='25d3e991f5637f5a', fullName='South West, England', name='South West', type='admin', country='United Kingdom', countryCode='GB')",
       "Place(id='10169cb2380221b0', fullName='Upton, England', name='Upton', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='758cf93327e58a4e', fullName='Anduze, France', name='Anduze', type='city', country='France', countryCode='FR')",
       "Place(id='6c3784993a540a38', fullName='Harlow, East', name='Harlow', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='01864a8a64df9dc4', fullName='Melbourne, Victoria', name='Melbourne', type='city', country='Australia', countryCode='AU')",
       "Place(id='1c3680c48401e703', fullName='Staines-upon-Thames, South East', name='Staines-upon-Thames', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='5568fcf97199b753', fullName='Luton, England', name='Luton', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='52376893bb80ba3d', fullName='Ashington, England', name='Ashington', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='006a72837c6cceb0', fullName='Brong-Ahafo, Ghana', name='Brong-Ahafo', type='admin', country='Ghana', countryCode='GH')",
       "Place(id='b49b3053b5c25bf5', fullName='Denver, CO', name='Denver', type='city', country='United States', countryCode='US')",
       "Place(id='82779978c58253a6', fullName='Albania', name='Albania', type='country', country='Albania', countryCode='AL')",
       "Place(id='4f854c83732cf4f5', fullName='Watford, East', name='Watford', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='d6539f049c4d05e8', fullName='Lowell, MA', name='Lowell', type='city', country='United States', countryCode='US')",
       "Place(id='09ba692cbddfc92c', fullName='Hammersmith, London', name='Hammersmith', type='city', country='United Kingdom', countryCode='GB')",
       "Place(id='50f2d0272381533f', fullName='East Midlands, England', name='East Midlands', type='admin', country='United Kingdom', countryCode='GB')",

In [184]:
with open('PLACE_TO_COUNTRY_MAP.pickle', 'rb') as handle:
    pmapping = pickle.load(handle)

In [185]:
with open('FAILED_PLACES.pickle', 'rb') as handle:
    pfailed = pickle.load(handle)

In [186]:
pmapping

{'Germiston, South Africa': 'South Africa',
 'South Africa': 'South Africa',
 'Dar es Salaam, Tanzania': 'Tanzania',
 'Accra, Ghana': 'Ghana',
 'Punjab, Pakistan': 'Pakistan',
 'Startforth, England': 'England',
 'Camberwell, London': 'England',
 'Rijiyar Zaki, Nigeria': 'Nigeria',
 'Manchester, England': 'England',
 'Dubai, United Arab Emirates': 'United Arab Emirates',
 'Washington, DC': 'United States',
 'Enfield, London': 'England',
 'South East, England': 'England',
 'Kumasi, Ghana': 'Ghana',
 'East, England': 'England',
 'Walkden, England': 'England',
 'Bahrain': 'Bahrain',
 'Nairobi, Kenya': 'Kenya',
 'Luwero, Uganda': 'Uganda',
 'Toronto, Ontario': 'Canada',
 'Port Harcourt, Nigeria': 'Nigeria',
 'Northampton, England': 'England',
 'ƒ∞stanbul, T√ºrkiye': 'T√ºrkiye',
 'Thunder Bay, Ontario': 'Canada',
 'Warrington, England': 'England',
 'Wales, England': 'Wales',
 'Evesham, England': 'England',
 'Braga, Portugal': 'Portugal',
 'Birmingham, England': 'England',
 'West Midlands, England': 'England',
 'Witney, England': 'England',
 'Tampere, Finland': 'Finland',
 'Hig√ºey, Dominican Republic': 'Dominican Republic',
 'Plymouth, England': 'England',
 'Benito Ju√°rez, Quintana Roo': 'Mexico',
 'Polesworth, England': 'England',
 'Innisfil, Ontario': 'Canada',
 'Kingswood, England': 'England',
 'Fingal, Ireland': 'Ireland',
 'Ikeja, Nigeria': 'Nigeria',
 'Iseyin, Nigeria': 'Nigeria',
 'Ayr, Scotland': 'Scotland',
 'London, England': 'England',
 'Lagos, Nigeria': 'Nigeria',
 'Mongolia': 'Mongolia',
 'Belfast, Northern Ireland': 'Northern Ireland',
 'East Orange, NJ': 'United States',
 'Warsaw, Poland': 'Poland',
 'Nea Alikarnassos, Greece': 'Greece',
 'Arkadi, Greece': 'Greece',
 'Nebraska, USA': 'United States',
 'Rotterdam, The Netherlands': 'The Netherlands',
 'Ilorin, Nigeria': 'Nigeria',
 'North West, England': 'England',
 'West Bromwich, England': 'England',
 'Islamabad, Pakistan': 'Pakistan',
 'Blyth, England': 'England',
 'Hartlepool, England': 'England',
 'Sydney, New South Wales': 'Australia',
 'Merrimack, NH': 'United States',
 'North East, England': 'England',
 'Gateshead, England': 'England',
 'Coningsby, England': 'England',
 'Denecrest, England': 'England',
 'High Beech, East': 'England',
 'East Kilbride, Scotland': 'Scotland',
 'Aziziah, Kingdom of Saudi Arabia': 'Saudi Arabia',
 'New Jersey, USA': 'United States',
 'Kakuma, Kenya': 'Kenya',
 'Dammam, Kingdom of Saudi Arabia': 'Saudi Arabia',
 'West Covina, CA': 'United States',
 'Kampala, Uganda': 'Uganda',
 'Al Khobar, Kingdom of Saudi Arabia': 'Saudi Arabia',
 'Federal Capital Territory, Nigeria': 'Nigeria',
 'Houston, TX': 'United States',
 'Bor√•s, Sverige': 'Sweden',
 'Rift Valley, Kenya': 'Kenya',
 'Heybridge, East': 'England',
 'Stafford, England': 'England',
 'Milton Keynes, England': 'England',
 'Valley Stream, NY': 'United States',
 'San Antonio, TX': 'United States',
 'Windcrest, TX': 'United States',
 'Canberra, Australian Capital Territory': 'Australia',
 'Ekpoma, Nigeria': 'Nigeria',
 'Lahore, Pakistan': 'Pakistan',
 'Wales, United Kingdom': 'Wales',
 'Croydon, London': 'England',
 'Pollen√ßa, Spain': 'Spain',
 'Rochester, South East': 'England',
 'Gatineau, Qu√©bec': 'Canada',
 'Abu Dhabi, United Arab Emirates': 'United Arab Emirates',
 'England, United Kingdom': 'England',
 'Louisville, KY': 'United States',
 'Banstead, South East': 'England',
 'Barnet, London': 'England',
 'Samaru, Nigeria': 'Nigeria',
 'Massachusetts, USA': 'United States',
 'Sompting, England': 'England',
 'Benin-City, Nigeria': 'Nigeria',
 'Belo Horizonte, Brazil': 'Brazil',
 'Kiama, New South Wales': 'Australia',
 'Port Hadlock-Irondale, WA': 'United States',
 'Bournemouth, England': 'England',
 'Poole, England': 'England',
 'Kensington, London': 'England',
 'Kano, Nigeria': 'Nigeria',
 'South West, England': 'England',
 'Upton, England': 'England',
 'Anduze, France': 'France',
 'Harlow, East': 'England',
 'Melbourne, Victoria': 'Australia',
 'Staines-upon-Thames, South East': 'England',
 'Ashington, England': 'England',
 'Denver, CO': 'United States',
 'Albania': 'Albania',
 'Watford, East': 'England',
 'Lowell, MA': 'United States',
 'Hammersmith, London': 'England',
 'East Midlands, England': 'England',
 'Florida, USA': 'United States',
 'Wandsworth, London': 'England',
 'San Francisco, CA': 'United States',
 'Wolverhampton, England': 'England',
 'Baltimore, MD': 'United States',
 'Albuquerque, NM': 'United States',
 'Dudley, England': 'England',
 'Wednesfield, England': 'England',
 'Dublin City, Ireland': 'Ireland',
 'Heswall, England': 'England',
 'Thika, Kenya': 'Kenya',
 'Islington, London': 'England',
 'Maghull, England': 'England',
 'Margate, England': 'England',
 'Las Cruces, NM': 'United States',
 'Warri, Nigeria': 'Nigeria',
 'Newbury, England': 'England',
 'Nolensville, TN': 'United States',
 'Lexington, SC': 'United States',
 'Southglenn, CO': 'United States',
 'Hanoi, Vietnam': 'Vietnam',
 'Hounslow, London': 'England',
 'Eltham, London': 'England',
 'Los Angeles, CA': 'United States',
 'Washington, USA': 'United States',
 'Nashville, TN': 'United States',
 'Northern Ireland, United Kingdom': 'Northern Ireland',
 'St Michael, MN': 'United States',
 'Bristol, England': 'England',
 'Mansfield, England': 'England',
 'Nottingham, England': 'England',
 'Carlton, England': 'England',
 'Hambrook, England': 'England',
 'Mitcheldean, England': 'England',
 'Meath, Ireland': 'Ireland',
 'Seville, Spain': 'Spain',
 'Luton, England': 'England',
 'Kaduna, Nigeria': 'Nigeria',
 'Hertford, East': 'England',
 'Southend-on-Sea, East': 'England',
 'Potten End, England': 'England',
 'Matabeleland South, Zimbabwe': 'Zimbabwe',
 'Urmston, England': 'England',
 'Pretoria, South Africa': 'South Africa',
 'Milnerton, South Africa': 'South Africa',
 'Grahamstown, South Africa': 'South Africa',
 'Colne, England': 'England',
 'Espoo, Suomi': 'Finland',
 'Glenrothes, Scotland': 'Scotland',
 'Yorkshire and The Humber, England': 'England',
 'Gillingham, England': 'England',
 'Rayleigh, East': 'England',
 'Bradford, England': 'England',
 'Brent, London': 'England',
 'Vƒ©nh Ph√∫c, Vietnam': 'Vietnam',
 'Sheffield, England': 'England',
 'Tottenham, London': 'England',
 'Cork, Ireland': 'Ireland',
 'South Dublin, Ireland': 'Ireland',
 '': 'None'}

In [187]:
pfailed

[]

In [188]:
replies["user_place_fullname"] = [re.search(r"fullName='(.*?)'", place).group(1) if pd.notna(place) and re.search(r"fullName='(.*?)'", place) else None for place in replies["place"]]

In [189]:
replies["user_place_fullname"].unique()

array([None, 'Maiduguri, Nigeria', 'Germiston, South Africa',
       'South Africa', 'Dar es Salaam, Tanzania', 'Accra, Ghana',
       'Kampala, Uganda', 'Punjab, Pakistan', 'Startforth, England',
       'Camberwell, London', 'Rijiyar Zaki, Nigeria',
       'Manchester, England', 'Dubai, United Arab Emirates',
       'Washington, DC', 'Enfield, London', 'South East, England',
       'Kumasi, Ghana', 'East, England', 'Walkden, England', 'Bahrain',
       'Nairobi, Kenya', 'Luwero, Uganda', 'Toronto, Ontario',
       'Port Harcourt, Nigeria', 'Northampton, England',
       'ƒ∞stanbul, T√ºrkiye', 'Warrington, England', 'Thunder Bay, Ontario',
       'Medan Denai, Indonesia', 'Wales, England', 'Evesham, England',
       'Ciudad Aut√≥noma de Buenos Aires, Argentina', 'Braga, Portugal',
       'Birmingham, England', 'West Midlands, England',
       'Plymouth, England', 'Witney, England', 'Tampere, Finland',
       'Hig√ºey, Dominican Republic', 'Carlton, England',
       'Benito Ju√°rez, Quintana Roo', 'South Dublin, Ireland',
       'Polesworth, England', 'Innisfil, Ontario', 'Kingswood, England',
       'Fingal, Ireland', 'Islington, London', 'Ikeja, Nigeria',
       'Iseyin, Nigeria', 'Paradise, NV', 'Ayr, Scotland', 'Queens, NY',
       'London, England', 'Lagos, Nigeria', 'Mongolia',
       'Clacton-on-Sea, England', 'Belfast, Northern Ireland',
       'Aguachica, Colombia', 'Warsaw, Poland', 'Imo, Nigeria',
       'East Orange, NJ', 'Oyarifa, Ghana', 'Nea Alikarnassos, Greece',
       'Kisumu, Kenya', 'Arkadi, Greece', 'Nebraska, USA',
       'Rotterdam, The Netherlands', 'Ilorin, Nigeria',
       'North West, England', 'West Bromwich, England',
       'Jeddah, Kingdom of Saudi Arabia', 'Islamabad, Pakistan',
       'Blyth, England', 'Hartlepool, England', 'Sydney, New South Wales',
       'Merrimack, NH', 'North East, England', 'Gateshead, England',
       'Coningsby, England', 'Qu√©bec, Canada', 'Denecrest, England',
       'High Beech, East', 'East Kilbride, Scotland',
       'Aziziah, Kingdom of Saudi Arabia', 'New Jersey, USA',
       'Kakuma, Kenya', 'Dammam, Kingdom of Saudi Arabia',
       'West Covina, CA', 'Northern Ireland, United Kingdom',
       'Al Khobar, Kingdom of Saudi Arabia',
       'Federal Capital Territory, Nigeria', 'Houston, TX',
       'Bor√•s, Sverige', 'Rift Valley, Kenya', 'Heybridge, East',
       'Stafford, England', 'Milton Keynes, England', 'Valley Stream, NY',
       'San Antonio, TX', 'Windcrest, TX',
       'Canberra, Australian Capital Territory', 'Ekpoma, Nigeria',
       'Lahore, Pakistan', 'Wales, United Kingdom', 'Croydon, London',
       'Pollen√ßa, Spain', 'Rochester, South East', 'Gatineau, Qu√©bec',
       'Goi√¢nia, Brazil', 'Abu Dhabi, United Arab Emirates',
       'England, United Kingdom', 'Louisville, KY',
       'Banstead, South East', 'Kano, Nigeria', 'Barnet, London',
       'Samaru, Nigeria', 'Massachusetts, USA', 'Sompting, England',
       'Benin-City, Nigeria', 'Belo Horizonte, Brazil',
       'Kiama, New South Wales', 'Port Hadlock-Irondale, WA',
       'Bournemouth, England', 'Poole, England', 'Kensington, London',
       'South West, England', 'Upton, England', 'Anduze, France',
       'Harlow, East', 'Melbourne, Victoria',
       'Staines-upon-Thames, South East', 'Luton, England',
       'Ashington, England', 'Brong-Ahafo, Ghana', 'Denver, CO',
       'Albania', 'Watford, East', 'Lowell, MA', 'Hammersmith, London',
       'East Midlands, England', 'Florida, USA', 'Cileungsi, Indonesia',
       'Wandsworth, London', 'San Francisco, CA',
       'Wolverhampton, England', 'Baltimore, MD',
       'Rio de Janeiro, Brazil', 'Albuquerque, NM', 'Dudley, England',
       'Wednesfield, England', 'Cibinong, Indonesia',
       'Dublin City, Ireland', 'Heswall, England', 'Thika, Kenya',
       'Liverpool, England', 'Alexandra, South Africa',
       'Maghull, England', 'Margate, England', 'Hackney, London',
       'Las Cruces, NM', 'Ghent, Belgium', 'Warri, Nigeria',
       'GrudziƒÖdz, Polska', 'Newbury, England', 'Nolensville, TN',
       'Broadstairs, England', 'Lexington, SC', 'Southglenn, CO',
       'Hanoi, Vietnam', 'Hounslow, London', 'Eltham, London',
       'Los Angeles, CA', 'Washington, USA', 'Nashville, TN',
       'St Michael, MN', 'Bristol, England', 'Mansfield, England',
       'Nottingham, England', 'Hambrook, England', 'Senegal',
       'Mitcheldean, England', 'Meath, Ireland', 'Seville, Spain',
       'Kaduna, Nigeria', 'Hertford, East', 'Southend-on-Sea, East',
       'Potten End, England', 'Matabeleland South, Zimbabwe',
       'Urmston, England', 'Pretoria, South Africa',
       'Milnerton, South Africa', 'Grahamstown, South Africa',
       'Colne, England', 'Burnley, England', 'Centurion, South Africa',
       'Espoo, Suomi', 'Glenrothes, Scotland', 'Sheffield, England',
       'Yorkshire and The Humber, England', 'Gillingham, England',
       'Rayleigh, East', 'Bradford, England', 'Tom√©, Chile',
       'Brent, London', 'Vƒ©nh Ph√∫c, Vietnam', 'Tottenham, London',
       'Cork, Ireland'], dtype=object)

In [193]:
replies["user_pcountry"] = replies["user_place_fullname"].map(pmapping)

In [194]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country,user_place_fullname,user_pcountry
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,England,None,NaN
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN,None,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN,None,NaN
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,...,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,None,None,NaN
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,United Kingdom,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,Nigeria,None,NaN
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,USA,None,NaN

In [195]:
replies["user_pcountry"].unique()

array([nan, 'South Africa', 'Tanzania', 'Ghana', 'Uganda', 'Pakistan',
       'England', 'Nigeria', 'United Arab Emirates', 'United States',
       'Bahrain', 'Kenya', 'Canada', 'T√ºrkiye', 'Wales', 'Portugal',
       'Finland', 'Dominican Republic', 'Mexico', 'Ireland', 'Scotland',
       'Mongolia', 'Northern Ireland', 'Poland', 'Greece',
       'The Netherlands', 'Australia', 'Saudi Arabia', 'Sweden', 'Spain',
       'Brazil', 'France', 'Albania', 'Vietnam', 'Zimbabwe'], dtype=object)

In [203]:
for i, reply in replies.iterrows():
    if pd.notna(reply["user_pcountry"]):
        replies.loc[i, "user_country"] = reply["user_pcountry"]

In [204]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country,user_place_fullname,user_pcountry
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,England,None,NaN
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN,None,NaN
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,NaN,None,NaN
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,...,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,None,None,NaN
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,United Kingdom,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,Nigeria,None,NaN
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,NaN,None,NaN
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,USA,None,NaN

In [205]:
replies["user_country"].unique()

array(['England', nan, 'None', 'United Kingdom', 'Nigeria',
       'Saudi Arabia', 'South Africa', 'USA', 'Turkey',
       'United Arab Emirates', 'Poland', 'Netherlands', 'India',
       'Australia', 'Canada', 'Spain', 'Kenya', 'Pakistan', 'Uganda',
       'Jamaica', 'Luxembourg', 'Tanzania', 'Malaysia', 'France',
       'Morocco', 'China', 'Kuwait', 'Brazil', 'Germany', 'Ireland',
       'Ghana', 'Vietnam', 'Qatar', 'Chile', 'Croatia', 'Denmark',
       'Angola', 'Bangladesh', 'Belgium', 'Mexico', 'Cyprus', 'Venezuela',
       'New Zealand', 'Scotland', 'Somalia', 'Austria', 'Israel',
       'Indonesia', 'Botswana', 'Cura√ßao', 'Bahrain', 'Finland',
       'Colombia', 'Argentina', 'Iceland', 'Greece', 'South Korea',
       'Norway', 'Czech Republic', 'Honduras', 'Mozambique', 'Zimbabwe',
       'Ecuador', 'Switzerland', 'United States', 'Egypt', 'Japan',
       'Northern Ireland', 'Wales', 'Mauritania', 'Georgia', 'Sweden',
       'Peru', 'Albania', 'Afghanistan', 'Africa', 'Italy', 'T√ºrkiye',
       'Slovenia', 'Serbia', 'Oman', 'Singapore', 'Gambia', 'Thailand',
       'Zambia', 'Namibia', 'Senegal', 'Monaco', 'Portugal', 'Montenegro',
       'Romania', 'Iraq', 'Hungary', 'Dominican Republic', 'Taiwan',
       'Costa Rica', 'Bahamas', 'Mauritius', 'Azerbaijan', 'Mongolia',
       'Hong Kong', 'Democratic Republic of the Congo', 'Jersey',
       'Bulgaria', 'eSwatini', 'Malta', 'Russia', 'Ivory Coast',
       'The Netherlands', 'Sudan', 'Seychelles', 'Puerto Rico',
       'South Sudan', 'Papua New Guinea', 'Cuba', 'Paraguay', 'Rwanda',
       'Madagascar', 'Palestine', 'Ethiopia', 'Earth', 'Cameroon',
       'Ukraine', 'Algeria', 'Nicaragua', 'Antarctica', 'Liberia',
       'Estonia', 'Guatemala', 'Macedonia', 'Sierra Leone', 'Benin',
       'Lesotho', 'Suriname', 'Tunisia', 'Philippines', 'Libya',
       'Lebanon', 'Uzbekistan', 'Bermuda', 'Malawi', 'M√©xico', 'Slovakia',
       'Nepal', 'Myanmar', 'Fiji', 'Uruguay', 'Panama',
       'Falkland Islands', 'Isle of Man', 'North Korea', 'Belarus',
       'Trinidad and Tobago', 'Niger', 'Mali', 'Kosovo', 'Burundi',
       'Bosnia and Herzegovina'], dtype=object)

In [206]:
len(['England', "nan", 'None', 'United Kingdom', 'Nigeria',
       'Saudi Arabia', 'South Africa', 'USA', 'Turkey',
       'United Arab Emirates', 'Poland', 'Netherlands', 'India',
       'Australia', 'Canada', 'Spain', 'Kenya', 'Pakistan', 'Uganda',
       'Jamaica', 'Luxembourg', 'Tanzania', 'Malaysia', 'France',
       'Morocco', 'China', 'Kuwait', 'Brazil', 'Germany', 'Ireland',
       'Ghana', 'Vietnam', 'Qatar', 'Chile', 'Croatia', 'Denmark',
       'Angola', 'Bangladesh', 'Belgium', 'Mexico', 'Cyprus', 'Venezuela',
       'New Zealand', 'Scotland', 'Somalia', 'Austria', 'Israel',
       'Indonesia', 'Botswana', 'Cura√ßao', 'Bahrain', 'Finland',
       'Colombia', 'Argentina', 'Iceland', 'Greece', 'South Korea',
       'Norway', 'Czech Republic', 'Honduras', 'Mozambique', 'Zimbabwe',
       'Ecuador', 'Switzerland', 'Egypt', 'Japan', 'Northern Ireland',
       'Wales', 'Mauritania', 'Georgia', 'Sweden', 'Peru', 'Albania',
       'Afghanistan', 'Africa', 'Italy', 'Slovenia', 'Serbia', 'Oman',
       'Singapore', 'Gambia', 'Thailand', 'Zambia', 'Namibia', 'Senegal',
       'Monaco', 'Portugal', 'Montenegro', 'Romania', 'Iraq', 'Hungary',
       'Taiwan', 'Costa Rica', 'Bahamas', 'Mauritius', 'Azerbaijan',
       'Hong Kong', 'Democratic Republic of the Congo', 'Jersey',
       'Bulgaria', 'eSwatini', 'Malta', 'Russia', 'Ivory Coast', 'Sudan',
       'Seychelles', 'Puerto Rico', 'South Sudan', 'Papua New Guinea',
       'Cuba', 'Paraguay', 'Rwanda', 'Madagascar', 'Palestine',
       'Mongolia', 'Ethiopia', 'Earth', 'Cameroon', 'Ukraine', 'Algeria',
       'Nicaragua', 'Antarctica', 'Liberia', 'Estonia', 'Guatemala',
       'Macedonia', 'Sierra Leone', 'Benin', 'Lesotho', 'Suriname',
       'Tunisia', 'Philippines', 'Libya', 'Lebanon', 'Uzbekistan',
       'Bermuda', 'Malawi', 'M√©xico', 'Slovakia', 'Nepal', 'Myanmar',
       'Fiji', 'Uruguay', 'Panama', 'Falkland Islands', 'Isle of Man',
       'North Korea', 'Belarus', 'Trinidad and Tobago', 'Niger', 'Mali',
       'Kosovo', 'Burundi', 'Bosnia and Herzegovina']), len(['England', "nan", 'None', 'United Kingdom', 'Nigeria',
       'Saudi Arabia', 'South Africa', 'USA', 'Turkey',
       'United Arab Emirates', 'Poland', 'Netherlands', 'India',
       'Australia', 'Canada', 'Spain', 'Kenya', 'Pakistan', 'Uganda',
       'Jamaica', 'Luxembourg', 'Tanzania', 'Malaysia', 'France',
       'Morocco', 'China', 'Kuwait', 'Brazil', 'Germany', 'Ireland',
       'Ghana', 'Vietnam', 'Qatar', 'Chile', 'Croatia', 'Denmark',
       'Angola', 'Bangladesh', 'Belgium', 'Mexico', 'Cyprus', 'Venezuela',
       'New Zealand', 'Scotland', 'Somalia', 'Austria', 'Israel',
       'Indonesia', 'Botswana', 'Cura√ßao', 'Bahrain', 'Finland',
       'Colombia', 'Argentina', 'Iceland', 'Greece', 'South Korea',
       'Norway', 'Czech Republic', 'Honduras', 'Mozambique', 'Zimbabwe',
       'Ecuador', 'Switzerland', 'United States', 'Egypt', 'Japan',
       'Northern Ireland', 'Wales', 'Mauritania', 'Georgia', 'Sweden',
       'Peru', 'Albania', 'Afghanistan', 'Africa', 'Italy', 'T√ºrkiye',
       'Slovenia', 'Serbia', 'Oman', 'Singapore', 'Gambia', 'Thailand',
       'Zambia', 'Namibia', 'Senegal', 'Monaco', 'Portugal', 'Montenegro',
       'Romania', 'Iraq', 'Hungary', 'Dominican Republic', 'Taiwan',
       'Costa Rica', 'Bahamas', 'Mauritius', 'Azerbaijan', 'Mongolia',
       'Hong Kong', 'Democratic Republic of the Congo', 'Jersey',
       'Bulgaria', 'eSwatini', 'Malta', 'Russia', 'Ivory Coast',
       'The Netherlands', 'Sudan', 'Seychelles', 'Puerto Rico',
       'South Sudan', 'Papua New Guinea', 'Cuba', 'Paraguay', 'Rwanda',
       'Madagascar', 'Palestine', 'Ethiopia', 'Earth', 'Cameroon',
       'Ukraine', 'Algeria', 'Nicaragua', 'Antarctica', 'Liberia',
       'Estonia', 'Guatemala', 'Macedonia', 'Sierra Leone', 'Benin',
       'Lesotho', 'Suriname', 'Tunisia', 'Philippines', 'Libya',
       'Lebanon', 'Uzbekistan', 'Bermuda', 'Malawi', 'M√©xico', 'Slovakia',
       'Nepal', 'Myanmar', 'Fiji', 'Uruguay', 'Panama',
       'Falkland Islands', 'Isle of Man', 'North Korea', 'Belarus',
       'Trinidad and Tobago', 'Niger', 'Mali', 'Kosovo', 'Burundi',
       'Bosnia and Herzegovina'])

(154, 158)

In [208]:
replies[(replies["user_country"].notna()) & (replies["user_country"] != "None")]

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team,user_country,user_place_fullname,user_pcountry
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,England,None,NaN
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,United Kingdom,None,NaN
7,2024-05-14 23:46:38+00:00,@ManCity @okx UP CITY,1.790529e+18,FreedomOnlineng,2013-04-24 14:18:08+00:00,en,0.0,NaN,NaN,"Lagos, Nigeria",...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,Nigeria,None,NaN
9,2024-05-14 20:58:09+00:00,@ManCity @okx Arsenal fans how you feeling? üòÇüòÇ...,1.790487e+18,_Rayed22,2021-06-03 22:31:41+00:00,en,61.0,NaN,NaN,ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑŸÖŸÜŸàÿ±ÿ©,...,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity,Saudi Arabia,None,NaN
11,2024-05-14 20:53:09+00:00,"@ManCity Thank you üôèüèæ for saving football, Lon...",1.790486e+18,Gold227303,2022-11-29 01:59:57+00:00,en,2.0,NaN,NaN,"London, England",...,NaN,2ba17e6d,1790485181561753856,2,0:2,spursofficial,mancity,England,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79564,2023-08-13 20:17:27+00:00,@SheffieldUnited @WilliamOsula @premierleague ...,1.690820e+18,carlpearce1,2011-03-26 08:04:52+00:00,en,1.0,NaN,NaN,"England, United Kingdom",...,NaN,55fd92c7,1690372043164815360,0,0:0,sheffieldunited,cpfc,England,None,NaN
79570,2023-08-12 16:07:46+00:00,@SheffieldUnited @WilliamOsula Gunna be some p...,1.690395e+18,samr36,2011-02-06 21:20:22+00:00,en,1.0,NaN,NaN,Sheffield,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,England,None,NaN
79571,2023-08-12 14:16:34+00:00,"@SheffieldUnited @WilliamOsula Your time, lad....",1.690367e+18,sarahwoolley79,2010-10-06 11:54:09+00:00,en,0.0,NaN,NaN,"Hedge End, England",...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,England,None,NaN
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,Nigeria,None,NaN
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc,USA,None,NaN

In [210]:
replies.to_csv("/home/jasmine/PROJECTS/research/data_scrape/LOCATED_REPLIES.csv", index=False)

/home/jasmine/miniconda3/lib/python3.11/site-packages/pandas/core/internals/blocks.py:2538: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)