In [191]:
import pandas as pd

In [192]:
parent_tweets = pd.read_csv("/home/jasmine/PROJECTS/research/data_scrape/PARENT_TWEETS_FILTERED.csv")

### Remove tweets from after FT

---

In [193]:
parent_tweets["datetime"] = pd.to_datetime(parent_tweets["datetime"])

In [194]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...

In [195]:
ft_indicators = ["FULL TIME", "FULL-TIME", "Full time", "Full-time"]

In [196]:
# get the tweet ids of tweets AFTER the full time tweets
parent_tweets[parent_tweets.tweet.str.contains("FULL-TIME")]

,datetime,club_handle,tweet_id,tweet,user_location,match_report
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
16,2024-05-11 13:28:13,mancity,1789286391328727064,FULL-TIME | A big win on the road! üí™\n\n‚ö™Ô∏è 0-4...,Etihad Stadium,/en/matches/4e211d29/Fulham-Manchester-City-Ma...
39,2024-05-04 18:27:09,mancity,1786824903670255808,FULL-TIME | Five-star City! üåü\n\nü©µ 5-1 üê∫ #ManC...,Etihad Stadium,/en/matches/5a9032bf/Manchester-City-Wolverham...
68,2024-04-28 17:26:19,mancity,1784635268546297981,FULL-TIME | Three more points! ‚ûï3Ô∏è‚É£\n\nüå≥ 0-2 ü©µ...,Etihad Stadium,/en/matches/80bbb25e/Nottingham-Forest-Manches...
86,2024-04-25 20:56:08,mancity,1783600905142546816,FULL-TIME | Victory secured in style! üôå\n\nüîµ 0...,Etihad Stadium,/en/matches/45bb8cac/Brighton-and-Hove-Albion-...
107,2024-04-13 15:55:14,mancity,1779176527524958263,FULL-TIME | A big home win! üí™\n\nü©µ 5-1 üëí #ManC...,Etihad Stadium,/en/matches/40128bc4/Manchester-City-Luton-Tow...
133,2024-04-06 13:29:11,mancity,1776603059096899810,FULL-TIME | A big away win! üí™\n\nü¶Ö 2-4 ‚ö™Ô∏è #Man...,Etihad Stadium,/en/matches/fca82852/Crystal-Palace-Manchester...
158,2024-04-03 21:11:43,mancity,1775632294889308249,FULL-TIME | A big win! üí™\n\n#ManCity | @okx ht...,Etihad Stadium,/en/matches/ae3ba8e8/Manchester-City-Aston-Vil...
181,2024-03-31 17:25:18,mancity,1774488150196285716,FULL-TIME | Nothing to separate the two sides ...,Etihad Stadium,/en/matches/76b4b194/Manchester-City-Arsenal-M...

In [197]:
full_time_pattern = "|".join(ft_indicators)
full_time_tweets = parent_tweets[parent_tweets['tweet'].str.contains(full_time_pattern, case=False)]

later_tweet_ids = []

for _, full_time_row in full_time_tweets.iterrows():
    full_time_date = full_time_row['datetime'].date()  # Get the date of the "FULL-TIME" tweet
    full_time_timestamp = full_time_row['datetime']  # Get the exact timestamp of the "FULL-TIME" tweet
    full_time_club = full_time_row["club_handle"]

    # Filter tweets on the same day with a later timestamp
    same_day_later_tweets = parent_tweets[
        (parent_tweets["club_handle"] == full_time_club) &
        (parent_tweets['datetime'].dt.date == full_time_date) & 
        (parent_tweets['datetime'] > full_time_timestamp) 
    ]
    
    later_tweet_ids.extend(same_day_later_tweets['tweet_id'].tolist())

In [198]:
len(later_tweet_ids)

0

In [199]:
later_tweet_ids

[]

In [200]:
parent_tweets[parent_tweets["tweet_id"].isin(later_tweet_ids)]

Empty DataFrame
Columns: [datetime, club_handle, tweet_id, tweet, user_location, match_report]
Index: []

In [201]:
parent_tweets = parent_tweets[~parent_tweets["tweet_id"].isin(later_tweet_ids)]

In [202]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...
...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...

In [203]:
parent_tweets.to_csv("/home/jasmine/PROJECTS/research/data_scrape/PARENT_TWEETS_FILTERED.csv", index=False)

In [252]:
replies = pd.read_csv("/home/jasmine/PROJECTS/research/data_scrape/REPLIES_W_LANG.csv")

In [253]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,user_description,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",Funniest Michigan Man ever. Also the spinal co...,109.0,False,False,NaN,2ba17e6d,1790486742132216048
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,Funny Clips ‚Ä¢ Funny Quotes ‚Ä¢ @Arsenal üî¥ ‚Ä¢ Ig &...,6970.0,False,False,NaN,2ba17e6d,1790486742132216048
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,The only app you‚Äôll need for 'all things crypt...,5293573.0,False,True,Business,2ba17e6d,1790486742132216048
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,UP THE VILLA! ‚úä,2423724.0,False,True,Business,2ba17e6d,1790486742132216048
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,a chill guy,452.0,False,True,NaN,2ba17e6d,1790486742132216048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,@sheffieldunited | @saints | #NewYorkForever,57.0,False,False,NaN,55fd92c7,1690365565234192385
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,NaN,0.0,False,False,NaN,55fd92c7,1690365565234192385
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,Content Creator | Graphics Designer | Writer |...,2038.0,False,False,NaN,55fd92c7,1690365565234192385
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,Dont believe everything you see on the interne...,94.0,False,False,NaN,55fd92c7,1690365565234192385
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",Exiled Blade. Workaholic. Proud Dad of Joe,312.0,False,False,NaN,55fd92c7,1690365565234192385

In [254]:
replies = replies[~replies["parent_tweet_id"].isin(later_tweet_ids)]

In [255]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,user_description,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",Funniest Michigan Man ever. Also the spinal co...,109.0,False,False,NaN,2ba17e6d,1790486742132216048
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,Funny Clips ‚Ä¢ Funny Quotes ‚Ä¢ @Arsenal üî¥ ‚Ä¢ Ig &...,6970.0,False,False,NaN,2ba17e6d,1790486742132216048
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,The only app you‚Äôll need for 'all things crypt...,5293573.0,False,True,Business,2ba17e6d,1790486742132216048
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,UP THE VILLA! ‚úä,2423724.0,False,True,Business,2ba17e6d,1790486742132216048
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,a chill guy,452.0,False,True,NaN,2ba17e6d,1790486742132216048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,@sheffieldunited | @saints | #NewYorkForever,57.0,False,False,NaN,55fd92c7,1690365565234192385
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,NaN,0.0,False,False,NaN,55fd92c7,1690365565234192385
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,Content Creator | Graphics Designer | Writer |...,2038.0,False,False,NaN,55fd92c7,1690365565234192385
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,Dont believe everything you see on the interne...,94.0,False,False,NaN,55fd92c7,1690365565234192385
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",Exiled Blade. Workaholic. Proud Dad of Joe,312.0,False,False,NaN,55fd92c7,1690365565234192385

In [256]:
# replies.to_csv("/home/jasmine/PROJECTS/research/data_scrape/REPLIES_NEW.csv", index=False)

---

### Correspond each tweet to an event

In [209]:
club_stats = pd.read_csv("/home/jasmine/PROJECTS/research/data_scrape/ALL_CLUB_STATS.csv")
club_stats

,league,season,team,game,date,time,round,day,venue,result,...,xG,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,match_report,Notes
0,ENG-Premier League,2324,Manchester City,2023-08-11 Burnley-Manchester City,2023-08-11,20:00:00,Matchweek 1,Fri,Away,W,...,1.9,0.3,65,21572,Kevin De Bruyne,4-2-3-1,5-4-1,Craig Pawson,/en/matches/3a6836b4/Burnley-Manchester-City-A...,NaN
1,ENG-Premier League,2324,Manchester City,2023-08-19 Manchester City-Newcastle Utd,2023-08-19,20:00:00,Matchweek 2,Sat,Home,W,...,1.0,0.3,59,53419,Kyle Walker,4-2-3-1,4-3-3,Robert Jones,/en/matches/0b8f50a5/Manchester-City-Newcastle...,NaN
2,ENG-Premier League,2324,Manchester City,2023-08-27 Sheffield Utd-Manchester City,2023-08-27,14:00:00,Matchweek 3,Sun,Away,W,...,3.5,0.7,79,31336,Kyle Walker,4-2-3-1,3-5-2,Jarred Gillett,/en/matches/0844ff10/Sheffield-United-Manchest...,NaN
3,ENG-Premier League,2324,Manchester City,2023-09-02 Manchester City-Fulham,2023-09-02,15:00:00,Matchweek 4,Sat,Home,W,...,2.2,1.4,68,52899,Kyle Walker,4-2-3-1,4-3-3,Michael Oliver,/en/matches/88066bdf/Manchester-City-Fulham-Se...,NaN
4,ENG-Premier League,2324,Manchester City,2023-09-16 West Ham-Manchester City,2023-09-16,15:00:00,Matchweek 5,Sat,Away,W,...,3.6,0.9,68,62475,Kyle Walker,4-2-3-1,4-2-3-1,Andy Madley,/en/matches/64c0a6e2/West-Ham-United-Mancheste...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,ENG-Premier League,2324,Sheffield Utd,2024-04-24 Manchester Utd-Sheffield Utd,2024-04-24,20:00:00,Matchweek 29,Wed,Away,L,...,0.8,2.9,29,73549,Oliver Arblaster,3-5-2,4-2-3-1,Michael Salisbury,/en/matches/70770e72/Manchester-United-Sheffie...,NaN
756,ENG-Premier League,2324,Sheffield Utd,2024-04-27 Newcastle Utd-Sheffield Utd,2024-04-27,15:00:00,Matchweek 35,Sat,Away,L,...,1.5,3.1,40,52196,Oliver Arblaster,3-5-2,4-3-3,Tony Harrington,/en/matches/e92d40be/Newcastle-United-Sheffiel...,NaN
757,ENG-Premier League,2324,Sheffield Utd,2024-05-04 Sheffield Utd-Nott'ham Forest,2024-05-04,15:00:00,Matchweek 36,Sat,Home,L,...,2.2,1.5,54,28516,Jack Robinson,3-5-2,4-2-3-1,Chris Kavanagh,/en/matches/91a2da3b/Sheffield-United-Nottingh...,NaN
758,ENG-Premier League,2324,Sheffield Utd,2024-05-11 Everton-Sheffield Utd,2024-05-11,15:00:00,Matchweek 37,Sat,Away,L,...,0.6,2.3,42,39221,Jack Robinson,3-5-2,4-4-1-1,Stuart Attwell,/en/matches/482e6ce4/Everton-Sheffield-United-...,NaN
759,ENG-Premier League,2324,Sheffield Utd,2024-05-19 Sheffield Utd-Tottenham,2024-05-19,16:00:00,Matchweek 38,Sun,Home,L,...,1.0,3.1,25,29116,Jack Robinson,5-3-2,4-2-3-1,Andy Madley,/en/matches/273a89b4/Sheffield-United-Tottenha...,NaN

In [210]:
events = pd.read_csv("/home/jasmine/PROJECTS/research/data_scrape/ALL_GAME_EVENTS.csv")
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d
...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10

In [211]:
parent_tweets["report_id"] = [rep.split("/")[3] for rep in parent_tweets["match_report"]]
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d
...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7

In [212]:
club_stats["report_id"] = [rep.split("/")[3] for rep in club_stats["match_report"]]
club_stats

,league,season,team,game,date,time,round,day,venue,result,...,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,match_report,Notes,report_id
0,ENG-Premier League,2324,Manchester City,2023-08-11 Burnley-Manchester City,2023-08-11,20:00:00,Matchweek 1,Fri,Away,W,...,0.3,65,21572,Kevin De Bruyne,4-2-3-1,5-4-1,Craig Pawson,/en/matches/3a6836b4/Burnley-Manchester-City-A...,NaN,3a6836b4
1,ENG-Premier League,2324,Manchester City,2023-08-19 Manchester City-Newcastle Utd,2023-08-19,20:00:00,Matchweek 2,Sat,Home,W,...,0.3,59,53419,Kyle Walker,4-2-3-1,4-3-3,Robert Jones,/en/matches/0b8f50a5/Manchester-City-Newcastle...,NaN,0b8f50a5
2,ENG-Premier League,2324,Manchester City,2023-08-27 Sheffield Utd-Manchester City,2023-08-27,14:00:00,Matchweek 3,Sun,Away,W,...,0.7,79,31336,Kyle Walker,4-2-3-1,3-5-2,Jarred Gillett,/en/matches/0844ff10/Sheffield-United-Manchest...,NaN,0844ff10
3,ENG-Premier League,2324,Manchester City,2023-09-02 Manchester City-Fulham,2023-09-02,15:00:00,Matchweek 4,Sat,Home,W,...,1.4,68,52899,Kyle Walker,4-2-3-1,4-3-3,Michael Oliver,/en/matches/88066bdf/Manchester-City-Fulham-Se...,NaN,88066bdf
4,ENG-Premier League,2324,Manchester City,2023-09-16 West Ham-Manchester City,2023-09-16,15:00:00,Matchweek 5,Sat,Away,W,...,0.9,68,62475,Kyle Walker,4-2-3-1,4-2-3-1,Andy Madley,/en/matches/64c0a6e2/West-Ham-United-Mancheste...,NaN,64c0a6e2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,ENG-Premier League,2324,Sheffield Utd,2024-04-24 Manchester Utd-Sheffield Utd,2024-04-24,20:00:00,Matchweek 29,Wed,Away,L,...,2.9,29,73549,Oliver Arblaster,3-5-2,4-2-3-1,Michael Salisbury,/en/matches/70770e72/Manchester-United-Sheffie...,NaN,70770e72
756,ENG-Premier League,2324,Sheffield Utd,2024-04-27 Newcastle Utd-Sheffield Utd,2024-04-27,15:00:00,Matchweek 35,Sat,Away,L,...,3.1,40,52196,Oliver Arblaster,3-5-2,4-3-3,Tony Harrington,/en/matches/e92d40be/Newcastle-United-Sheffiel...,NaN,e92d40be
757,ENG-Premier League,2324,Sheffield Utd,2024-05-04 Sheffield Utd-Nott'ham Forest,2024-05-04,15:00:00,Matchweek 36,Sat,Home,L,...,1.5,54,28516,Jack Robinson,3-5-2,4-2-3-1,Chris Kavanagh,/en/matches/91a2da3b/Sheffield-United-Nottingh...,NaN,91a2da3b
758,ENG-Premier League,2324,Sheffield Utd,2024-05-11 Everton-Sheffield Utd,2024-05-11,15:00:00,Matchweek 37,Sat,Away,L,...,2.3,42,39221,Jack Robinson,3-5-2,4-4-1-1,Stuart Attwell,/en/matches/482e6ce4/Everton-Sheffield-United-...,NaN,482e6ce4
759,ENG-Premier League,2324,Sheffield Utd,2024-05-19 Sheffield Utd-Tottenham,2024-05-19,16:00:00,Matchweek 38,Sun,Home,L,...,3.1,25,29116,Jack Robinson,5-3-2,4-2-3-1,Andy Madley,/en/matches/273a89b4/Sheffield-United-Tottenha...,NaN,273a89b4

In [213]:
# give each parent tweet a kickoff time
parent_tweets["ko_time"] = [club_stats[club_stats["report_id"] == rep_id]["date"].values[0] + " " + club_stats[club_stats["report_id"] == rep_id]["time"].values[0] for rep_id in parent_tweets["report_id"]]

In [214]:
parent_tweets["ko_time"]

0       2024-05-14 20:00:00
1       2024-05-14 20:00:00
2       2024-05-14 20:00:00
3       2024-05-14 20:00:00
4       2024-05-14 20:00:00
               ...
9908    2023-08-12 15:00:00
9909    2023-08-12 15:00:00
9910    2023-08-12 15:00:00
9911    2023-08-12 15:00:00
9912    2023-08-12 15:00:00
Name: ko_time, Length: 9913, dtype: object

In [215]:
parent_tweets["ko_time"] = pd.to_datetime(parent_tweets["ko_time"]) - pd.to_timedelta(1, unit="h")

In [216]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00
...,...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00

In [217]:
parent_tweets["mins_after_ko"] = ((parent_tweets['datetime'] - parent_tweets['ko_time']).dt.total_seconds() / 60).astype(int)

In [218]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106
...,...,...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,37
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,31
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,25
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,12
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,1

In [219]:
parent_tweets[parent_tweets["report_id"] == "2ba17e6d"]

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106
5,2024-05-14 20:42:41,mancity,1790482891807305747,"MASSIVE SAVE, STEFAN!!!",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,102
6,2024-05-14 20:26:01,mancity,1790478696509215034,69. CITY SUBS | A double change üîÑ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,86
7,2024-05-14 20:22:13,mancity,1790477742498083154,üëëüîóüéØ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity https://t.co/gJocsk6ZST,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,82
8,2024-05-14 20:10:49,mancity,1790474871274631371,54. WE'VE SCORED A LEAGUE GOAL AT TOTTENHAM! üôå...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,70
9,2024-05-14 20:08:12,mancity,1790474214958338099,HAAAALAANNDDDDD!!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity htt...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68
10,2024-05-14 20:02:04,mancity,1790472668321321273,SECOND HALF | Let's do this! üí™\n\nFollow live üëá,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,62
11,2024-05-14 19:47:13,mancity,1790468930542219732,Level after 45 ‚è±\n\nJoin the Matchday Live tea...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,47
12,2024-05-14 19:45:40,mancity,1790468544586514736,HALF-TIME | Goalless at the break ‚öñÔ∏è\n\n‚ö™Ô∏è 0-0...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,45
13,2024-05-14 19:30:53,mancity,1790464823945490865,Nothing to separate us so far üîí\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30
14,2024-05-14 19:17:10,mancity,1790461372087570636,üáßüá™ü™Ñ\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #ManCity https://t.co/IFadcAz9sc,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,17
15,2024-05-14 19:00:35,mancity,1790457198461547007,"KICK-OFF | COME ON, CITY!!!! ü©µ\n\nFollow live üëá",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0
1687,2024-05-14 20:57:51,spursofficial,1790486709844525567,Full-time at @SpursStadium ‚è±Ô∏è https://t.co/kWG...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117
1688,2024-05-14 20:49:09,spursofficial,1790484520359075909,A Spurs debut for Mikey Moore ü§ç\n\n#TOTMCI // ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109
1689,2024-05-14 20:47:37,spursofficial,1790484131765199328,Haaland converts from the penalty spot.\n\n#TO...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107
1690,2024-05-14 20:41:38,spursofficial,1790482629021634949,Gio and Skippy are on for the closing stages üîÑ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,101
1691,2024-05-14 20:29:08,spursofficial,1790479482588954744,Deki comes close to a leveller üëä https://t.co/...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,89
1692,2024-05-14 20:11:58,spursofficial,1790475161025565038,Our first change of the evening as Deki replac...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,71
1693,2024-05-14 20:08:03,spursofficial,1790474177138266594,Haaland scores for City.\n\n#TOTMCI // 0-1,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68
1694,2024-05-14 20:03:24,spursofficial,1790473006906474782,Vic keeps out De Bruyne with a fantastic save! üï∏Ô∏è,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,63
1695,2024-05-14 20:01:56,spursofficial,1790472634288734716,Back to work in N17 ‚úä,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,61
1696,2024-05-14 19:46:18,spursofficial,1790468699868025264,Goalless at the interval ‚è∏Ô∏è https://t.co/A1BdU...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,46
1697,2024-05-14 19:30:54,spursofficial,1790464824863826339,Level after the opening 3Ô∏è‚É£0Ô∏è‚É£ minutes üëä https...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30
1698,2024-05-14 19:18:41,spursofficial,1790461753530163444,üåü https://t.co/9oxvN2NkmA,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,18
1699,2024-05-14 19:06:07,spursofficial,1790458589666025749,Lolo is denied by a superb Ederson save! üß§,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,6
1700,2024-05-14 19:05:44,spursofficial,1790458494312710390,ü´∂ https://t.co/859glKQVeP,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,5
1701,2024-05-14 19:00:22,spursofficial,1790457143465795638,COME ON YOU SPURS! ü§ç,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0

In [220]:
events[events["game_id"] == "2ba17e6d"]

,league,season,game,team,minute,score,player1,player2,event_type,game_id
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d
5,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Stefan Ortega,Ederson,substitute_in,2ba17e6d
6,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Jeremy Doku,Kevin De Bruyne,substitute_in,2ba17e6d
7,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,70,0:1,Mateo Kovaƒçiƒá,NaN,yellow_card,2ba17e6d
8,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Giovani Lo Celso,Pape Matar Sarr,substitute_in,2ba17e6d
9,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Oliver Skipp,Pierre H√∏jbjerg,substitute_in,2ba17e6d
10,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,88,0:1,Phil Foden,NaN,yellow_card,2ba17e6d
11,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+1,0:2,Erling Haaland,NaN,penalty_goal,2ba17e6d
12,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+10,0:2,Bernardo Silva,NaN,yellow_card,2ba17e6d
13,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,90+2,0:2,Mikey Moore,James Maddison,substitute_in,2ba17e6d
14,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+5,0:2,Juli√°n √Ålvarez,Erling Haaland,substitute_in,2ba17e6d

In [221]:
events["event_type"].unique()

array(['yellow_card', 'goal', 'substitute_in', 'penalty_goal',
       'yellow_red_card', 'own_goal', 'penalty_miss', 'red_card'],
      dtype=object)

In [222]:
events.dtypes

league        object
season         int64
game          object
team          object
minute        object
score         object
player1       object
player2       object
event_type    object
game_id       object
dtype: object

In [223]:
def convert_minute(minute):
    if '+' in minute:
        base_minute, added_time = minute.split('+')
        return int(base_minute) + int(added_time)
    else:
        return int(minute)

In [224]:
events["minute_eng"] = events['minute'].apply(convert_minute)

In [225]:
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,51
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,55
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,57
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,63
...,...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10,80
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10,83
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10,85
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10,86
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10,88

In [226]:
events[events["game_id"] == "2ba17e6d"]

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,51
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,55
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,57
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,63
5,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Stefan Ortega,Ederson,substitute_in,2ba17e6d,69
6,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Jeremy Doku,Kevin De Bruyne,substitute_in,2ba17e6d,69
7,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,70,0:1,Mateo Kovaƒçiƒá,NaN,yellow_card,2ba17e6d,70
8,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Giovani Lo Celso,Pape Matar Sarr,substitute_in,2ba17e6d,85
9,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Oliver Skipp,Pierre H√∏jbjerg,substitute_in,2ba17e6d,85
10,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,88,0:1,Phil Foden,NaN,yellow_card,2ba17e6d,88
11,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+1,0:2,Erling Haaland,NaN,penalty_goal,2ba17e6d,91
12,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+10,0:2,Bernardo Silva,NaN,yellow_card,2ba17e6d,100
13,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,90+2,0:2,Mikey Moore,James Maddison,substitute_in,2ba17e6d,92
14,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+5,0:2,Juli√°n √Ålvarez,Erling Haaland,substitute_in,2ba17e6d,95

In [227]:
def add_ht(minute):
    if int(minute) > 45:
        return int(minute) + 15
    else:
        return int(minute)

In [228]:
events["minute_eng"] = events['minute_eng'].apply(add_ht)

In [229]:
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,66
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,70
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,72
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,78
...,...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10,95
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10,98
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10,100
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10,101
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10,103

In [230]:
club_names = ["Manchester City",
              "Arsenal",
              "Liverpool",
              "Aston Villa",
              "Tottenham Hotspur",
              "Chelsea",
              "Newcastle United",
              "Manchester United",
              "West Ham United",
              "Crystal Palace",
              "Brighton & Hove Albion",
              "Bournemouth",
              "Fulham",
              "Wolverhampton Wanderers",
              "Everton",
              "Brentford",
              "Nottingham Forest",
              "Luton Town",
              "Burnley",
              "Sheffield United"]
club_handles = ["mancity",
                "arsenal",
                "lfc",
                "avfcofficial",
                "spursofficial",
                "chelseafc",
                "nufc",
                "manutd",
                "westham",
                "cpfc",
                "officialbhafc",
                "afcbournemouth",
                "fulhamfc",
                "wolves",
                "everton",
                "brentfordfc",
                "nffc",
                "lutontown",
                "burnleyofficial",
                "sheffieldunited"]
club_mapping = dict(zip(club_names, club_handles))

In [231]:
club_mapping

{'Manchester City': 'mancity',
 'Arsenal': 'arsenal',
 'Liverpool': 'lfc',
 'Aston Villa': 'avfcofficial',
 'Tottenham Hotspur': 'spursofficial',
 'Chelsea': 'chelseafc',
 'Newcastle United': 'nufc',
 'Manchester United': 'manutd',
 'West Ham United': 'westham',
 'Crystal Palace': 'cpfc',
 'Brighton & Hove Albion': 'officialbhafc',
 'Bournemouth': 'afcbournemouth',
 'Fulham': 'fulhamfc',
 'Wolverhampton Wanderers': 'wolves',
 'Everton': 'everton',
 'Brentford': 'brentfordfc',
 'Nottingham Forest': 'nffc',
 'Luton Town': 'lutontown',
 'Burnley': 'burnleyofficial',
 'Sheffield United': 'sheffieldunited'}

In [232]:
events["handle"] = events["team"].map(club_mapping)

In [233]:
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng,handle
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36,spursofficial
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,66,mancity
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,70,spursofficial
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,72,spursofficial
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,78,spursofficial
...,...,...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10,95,sheffieldunited
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10,98,sheffieldunited
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10,100,sheffieldunited
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10,101,mancity
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10,103,mancity

In [234]:
parent_tweets["score"] = None

In [235]:
for i, tweet in parent_tweets.iterrows(): 
    game_events = events[(events["game_id"] == tweet["report_id"]) & (events["handle"] == tweet["club_handle"])]
    recent_events = game_events[tweet["mins_after_ko"] >= game_events["minute_eng"]]

    if not recent_events.empty: 
        most_recent_event = recent_events.iloc[-1]
        parent_tweets.at[i, "score"] = most_recent_event["score"]

    else: 
        parent_tweets.at[i, "score"] = "0:0"

In [236]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko,score
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111,0:2
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106,0:2
...,...,...,...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,37,0:0
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,31,0:0
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,25,0:0
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,12,0:0
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,1,0:0

In [237]:
parent_tweets[parent_tweets["report_id"] == "2ba17e6d"]

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko,score
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111,0:2
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106,0:2
5,2024-05-14 20:42:41,mancity,1790482891807305747,"MASSIVE SAVE, STEFAN!!!",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,102,0:1
6,2024-05-14 20:26:01,mancity,1790478696509215034,69. CITY SUBS | A double change üîÑ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,86,0:1
7,2024-05-14 20:22:13,mancity,1790477742498083154,üëëüîóüéØ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity https://t.co/gJocsk6ZST,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,82,0:1
8,2024-05-14 20:10:49,mancity,1790474871274631371,54. WE'VE SCORED A LEAGUE GOAL AT TOTTENHAM! üôå...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,70,0:1
9,2024-05-14 20:08:12,mancity,1790474214958338099,HAAAALAANNDDDDD!!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity htt...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68,0:1
10,2024-05-14 20:02:04,mancity,1790472668321321273,SECOND HALF | Let's do this! üí™\n\nFollow live üëá,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,62,0:0
11,2024-05-14 19:47:13,mancity,1790468930542219732,Level after 45 ‚è±\n\nJoin the Matchday Live tea...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,47,0:0
12,2024-05-14 19:45:40,mancity,1790468544586514736,HALF-TIME | Goalless at the break ‚öñÔ∏è\n\n‚ö™Ô∏è 0-0...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,45,0:0
13,2024-05-14 19:30:53,mancity,1790464823945490865,Nothing to separate us so far üîí\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30,0:0
14,2024-05-14 19:17:10,mancity,1790461372087570636,üáßüá™ü™Ñ\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #ManCity https://t.co/IFadcAz9sc,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,17,0:0
15,2024-05-14 19:00:35,mancity,1790457198461547007,"KICK-OFF | COME ON, CITY!!!! ü©µ\n\nFollow live üëá",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0,0:0
1687,2024-05-14 20:57:51,spursofficial,1790486709844525567,Full-time at @SpursStadium ‚è±Ô∏è https://t.co/kWG...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2
1688,2024-05-14 20:49:09,spursofficial,1790484520359075909,A Spurs debut for Mikey Moore ü§ç\n\n#TOTMCI // ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2
1689,2024-05-14 20:47:37,spursofficial,1790484131765199328,Haaland converts from the penalty spot.\n\n#TO...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2
1690,2024-05-14 20:41:38,spursofficial,1790482629021634949,Gio and Skippy are on for the closing stages üîÑ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,101,0:1
1691,2024-05-14 20:29:08,spursofficial,1790479482588954744,Deki comes close to a leveller üëä https://t.co/...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,89,0:1
1692,2024-05-14 20:11:58,spursofficial,1790475161025565038,Our first change of the evening as Deki replac...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,71,0:1
1693,2024-05-14 20:08:03,spursofficial,1790474177138266594,Haaland scores for City.\n\n#TOTMCI // 0-1,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68,0:0
1694,2024-05-14 20:03:24,spursofficial,1790473006906474782,Vic keeps out De Bruyne with a fantastic save! üï∏Ô∏è,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,63,0:0
1695,2024-05-14 20:01:56,spursofficial,1790472634288734716,Back to work in N17 ‚úä,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,61,0:0
1696,2024-05-14 19:46:18,spursofficial,1790468699868025264,Goalless at the interval ‚è∏Ô∏è https://t.co/A1BdU...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,46,0:0
1697,2024-05-14 19:30:54,spursofficial,1790464824863826339,Level after the opening 3Ô∏è‚É£0Ô∏è‚É£ minutes üëä https...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30,0:0
1698,2024-05-14 19:18:41,spursofficial,1790461753530163444,üåü https://t.co/9oxvN2NkmA,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,18,0:0
1699,2024-05-14 19:06:07,spursofficial,1790458589666025749,Lolo is denied by a superb Ederson save! üß§,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,6,0:0
1700,2024-05-14 19:05:44,spursofficial,1790458494312710390,ü´∂ https://t.co/859glKQVeP,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,5,0:0
1701,2024-05-14 19:00:22,spursofficial,1790457143465795638,COME ON YOU SPURS! ü§ç,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0,0:0

In [238]:
events[events["game_id"] == "2ba17e6d"]

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng,handle
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36,spursofficial
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,66,mancity
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,70,spursofficial
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,72,spursofficial
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,78,spursofficial
5,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Stefan Ortega,Ederson,substitute_in,2ba17e6d,84,mancity
6,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,69,0:1,Jeremy Doku,Kevin De Bruyne,substitute_in,2ba17e6d,84,mancity
7,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,70,0:1,Mateo Kovaƒçiƒá,NaN,yellow_card,2ba17e6d,85,mancity
8,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Giovani Lo Celso,Pape Matar Sarr,substitute_in,2ba17e6d,100,spursofficial
9,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,85,0:1,Oliver Skipp,Pierre H√∏jbjerg,substitute_in,2ba17e6d,100,spursofficial
10,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,88,0:1,Phil Foden,NaN,yellow_card,2ba17e6d,103,mancity
11,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+1,0:2,Erling Haaland,NaN,penalty_goal,2ba17e6d,106,mancity
12,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+10,0:2,Bernardo Silva,NaN,yellow_card,2ba17e6d,115,mancity
13,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,90+2,0:2,Mikey Moore,James Maddison,substitute_in,2ba17e6d,107,spursofficial
14,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,90+5,0:2,Juli√°n √Ålvarez,Erling Haaland,substitute_in,2ba17e6d,110,mancity

In [239]:
# add margin
s = "2024-03-30 Sheffield Utd-Fulham"
" ".join(s.split(" ")[1:]).split("-")

['Sheffield Utd', 'Fulham']

In [240]:
events["home_team"] = [" ".join(s.split(" ")[1:]).split("-")[0] for s in events["game"]]
events["away_team"] = [" ".join(s.split(" ")[1:]).split("-")[-1] for s in events["game"]]
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng,handle,home_team,away_team
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36,spursofficial,Tottenham,Manchester City
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,66,mancity,Tottenham,Manchester City
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,70,spursofficial,Tottenham,Manchester City
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,72,spursofficial,Tottenham,Manchester City
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,78,spursofficial,Tottenham,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10,95,sheffieldunited,Sheffield Utd,Manchester City
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10,98,sheffieldunited,Sheffield Utd,Manchester City
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10,100,sheffieldunited,Sheffield Utd,Manchester City
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10,101,mancity,Sheffield Utd,Manchester City
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10,103,mancity,Sheffield Utd,Manchester City

In [241]:
club_names = ["Manchester City",
              "Arsenal",
              "Liverpool",
              "Aston Villa",
              "Tottenham",
              "Chelsea",
              "Newcastle Utd",
              "Manchester Utd",
              "West Ham",
              "Crystal Palace",
              "Brighton",
              "Bournemouth",
              "Fulham",
              "Wolves",
              "Everton",
              "Brentford",
              "Nott'ham Forest",
              "Luton Town",
              "Burnley",
              "Sheffield Utd"]
club_handles = ["mancity",
                "arsenal",
                "lfc",
                "avfcofficial",
                "spursofficial",
                "chelseafc",
                "nufc",
                "manutd",
                "westham",
                "cpfc",
                "officialbhafc",
                "afcbournemouth",
                "fulhamfc",
                "wolves",
                "everton",
                "brentfordfc",
                "nffc",
                "lutontown",
                "burnleyofficial",
                "sheffieldunited"]
club_mapping = dict(zip(club_names, club_handles))

In [242]:
events["home_team"] = [club_mapping[name] for name in events["home_team"]]
events["away_team"] = [club_mapping[name] for name in events["away_team"]]
events

,league,season,game,team,minute,score,player1,player2,event_type,game_id,minute_eng,handle,home_team,away_team
0,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,36,0:0,Rodrigo Bentancur,NaN,yellow_card,2ba17e6d,36,spursofficial,spursofficial,mancity
1,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Manchester City,51,0:1,Erling Haaland,Kevin De Bruyne,goal,2ba17e6d,66,mancity,spursofficial,mancity
2,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,55,0:1,Dejan Kulusevski,Rodrigo Bentancur,substitute_in,2ba17e6d,70,spursofficial,spursofficial,mancity
3,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,57,0:1,Pape Matar Sarr,NaN,yellow_card,2ba17e6d,72,spursofficial,spursofficial,mancity
4,ENG-Premier League,2324,2024-05-14 Tottenham-Manchester City,Tottenham Hotspur,63,0:1,Cristian Romero,NaN,yellow_card,2ba17e6d,78,spursofficial,spursofficial,mancity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5743,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,80,0:1,Chris Basham,Oliver Norwood,substitute_in,0844ff10,95,sheffieldunited,sheffieldunited,mancity
5744,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,83,0:1,John Egan,NaN,yellow_card,0844ff10,98,sheffieldunited,sheffieldunited,mancity
5745,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Sheffield United,85,1:1,Jayden Bogle,NaN,goal,0844ff10,100,sheffieldunited,sheffieldunited,mancity
5746,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,86,1:1,Phil Foden,Mateo Kovaƒçiƒá,substitute_in,0844ff10,101,mancity,sheffieldunited,mancity
5747,ENG-Premier League,2324,2023-08-27 Sheffield Utd-Manchester City,Manchester City,88,1:2,Rodri,Phil Foden,goal,0844ff10,103,mancity,sheffieldunited,mancity

In [243]:
parent_tweets["home_team"] = None
parent_tweets["away_team"] = None

In [246]:
for i, tweet in parent_tweets.iterrows(): 
    game_events = events[(events["game_id"] == tweet["report_id"])]
    home_team = game_events["home_team"].values[0]
    away_team = game_events["away_team"].values[0]

    parent_tweets.at[i, "home_team"] = home_team
    parent_tweets.at[i, "away_team"] = away_team

In [247]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko,score,home_team,away_team
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2,spursofficial,mancity
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111,0:2,spursofficial,mancity
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2,spursofficial,mancity
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2,spursofficial,mancity
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106,0:2,spursofficial,mancity
...,...,...,...,...,...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,37,0:0,sheffieldunited,cpfc
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,31,0:0,sheffieldunited,cpfc
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,25,0:0,sheffieldunited,cpfc
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,12,0:0,sheffieldunited,cpfc
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,1,0:0,sheffieldunited,cpfc

In [248]:
parent_tweets["margin"] = None

In [249]:
for i, tweet in parent_tweets.iterrows(): 

    scores = tweet["score"].split(":")

    if tweet["club_handle"] == tweet["home_team"]: 
        parent_tweets.at[i, "margin"] = int(scores[0]) - int(scores[1])

    else: 
        parent_tweets.at[i, "margin"] = int(scores[1]) - int(scores[0])

In [250]:
parent_tweets

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko,score,home_team,away_team,margin
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2,spursofficial,mancity,2
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111,0:2,spursofficial,mancity,2
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2,spursofficial,mancity,2
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2,spursofficial,mancity,2
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106,0:2,spursofficial,mancity,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9908,2023-08-12 14:37:55,sheffieldunited,1690372043164815360,"Will Osula, giving it everything on his Premie...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,37,0:0,sheffieldunited,cpfc,0
9909,2023-08-12 14:31:53,sheffieldunited,1690370526500241408,Ollie N in action. üéØ https://t.co/rI4intmCoz,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,31,0:0,sheffieldunited,cpfc,0
9910,2023-08-12 14:25:07,sheffieldunited,1690368822346158080,Palace have the ball in the net after Wes parr...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,25,0:0,sheffieldunited,cpfc,0
9911,2023-08-12 14:12:10,sheffieldunited,1690365565234192385,"Looking dangerous in the early stages, @Willia...","Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,12,0:0,sheffieldunited,cpfc,0
9912,2023-08-12 14:01:17,sheffieldunited,1690362823975546880,Our @premierleague season gets underway at Bra...,"Sheffield, UK",/en/matches/55fd92c7/Sheffield-United-Crystal-...,55fd92c7,2023-08-12 14:00:00,1,0:0,sheffieldunited,cpfc,0

In [251]:
parent_tweets[parent_tweets["report_id"] == "2ba17e6d"]

,datetime,club_handle,tweet_id,tweet,user_location,match_report,report_id,ko_time,mins_after_ko,score,home_team,away_team,margin
0,2024-05-14 20:57:59,mancity,1790486742132216048,FULL-TIME | A huge win!! ‚úä\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCi...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2,spursofficial,mancity,2
1,2024-05-14 20:51:47,mancity,1790485181561753856,90+5. CITY SUB | A change up top üîÑ\n\n‚ö™Ô∏è 0-2 ‚ö°...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,111,0:2,spursofficial,mancity,2
2,2024-05-14 20:49:18,mancity,1790484554513306039,90+3. IT'S TWO!!!! üôå\n\n@JeremyDoku does brill...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2,spursofficial,mancity,2
3,2024-05-14 20:47:39,mancity,1790484139767902347,GET INNNNNN!!!!!!\n\n‚ö™Ô∏è 0-2 ‚ö°Ô∏è #ManCity https:...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2,spursofficial,mancity,2
4,2024-05-14 20:46:14,mancity,1790483783793197503,90. PENALTY TO CITY!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,106,0:2,spursofficial,mancity,2
5,2024-05-14 20:42:41,mancity,1790482891807305747,"MASSIVE SAVE, STEFAN!!!",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,102,0:1,spursofficial,mancity,1
6,2024-05-14 20:26:01,mancity,1790478696509215034,69. CITY SUBS | A double change üîÑ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,86,0:1,spursofficial,mancity,1
7,2024-05-14 20:22:13,mancity,1790477742498083154,üëëüîóüéØ\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity https://t.co/gJocsk6ZST,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,82,0:1,spursofficial,mancity,1
8,2024-05-14 20:10:49,mancity,1790474871274631371,54. WE'VE SCORED A LEAGUE GOAL AT TOTTENHAM! üôå...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,70,0:1,spursofficial,mancity,1
9,2024-05-14 20:08:12,mancity,1790474214958338099,HAAAALAANNDDDDD!!!!!\n\n‚ö™Ô∏è 0-1 ‚ö°Ô∏è #ManCity htt...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68,0:1,spursofficial,mancity,1
10,2024-05-14 20:02:04,mancity,1790472668321321273,SECOND HALF | Let's do this! üí™\n\nFollow live üëá,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,62,0:0,spursofficial,mancity,0
11,2024-05-14 19:47:13,mancity,1790468930542219732,Level after 45 ‚è±\n\nJoin the Matchday Live tea...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,47,0:0,spursofficial,mancity,0
12,2024-05-14 19:45:40,mancity,1790468544586514736,HALF-TIME | Goalless at the break ‚öñÔ∏è\n\n‚ö™Ô∏è 0-0...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,45,0:0,spursofficial,mancity,0
13,2024-05-14 19:30:53,mancity,1790464823945490865,Nothing to separate us so far üîí\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #...,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30,0:0,spursofficial,mancity,0
14,2024-05-14 19:17:10,mancity,1790461372087570636,üáßüá™ü™Ñ\n\n‚ö™Ô∏è 0-0 ‚ö°Ô∏è #ManCity https://t.co/IFadcAz9sc,Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,17,0:0,spursofficial,mancity,0
15,2024-05-14 19:00:35,mancity,1790457198461547007,"KICK-OFF | COME ON, CITY!!!! ü©µ\n\nFollow live üëá",Etihad Stadium,/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0,0:0,spursofficial,mancity,0
1687,2024-05-14 20:57:51,spursofficial,1790486709844525567,Full-time at @SpursStadium ‚è±Ô∏è https://t.co/kWG...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,117,0:2,spursofficial,mancity,-2
1688,2024-05-14 20:49:09,spursofficial,1790484520359075909,A Spurs debut for Mikey Moore ü§ç\n\n#TOTMCI // ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,109,0:2,spursofficial,mancity,-2
1689,2024-05-14 20:47:37,spursofficial,1790484131765199328,Haaland converts from the penalty spot.\n\n#TO...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,107,0:2,spursofficial,mancity,-2
1690,2024-05-14 20:41:38,spursofficial,1790482629021634949,Gio and Skippy are on for the closing stages üîÑ...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,101,0:1,spursofficial,mancity,-1
1691,2024-05-14 20:29:08,spursofficial,1790479482588954744,Deki comes close to a leveller üëä https://t.co/...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,89,0:1,spursofficial,mancity,-1
1692,2024-05-14 20:11:58,spursofficial,1790475161025565038,Our first change of the evening as Deki replac...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,71,0:1,spursofficial,mancity,-1
1693,2024-05-14 20:08:03,spursofficial,1790474177138266594,Haaland scores for City.\n\n#TOTMCI // 0-1,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,68,0:0,spursofficial,mancity,0
1694,2024-05-14 20:03:24,spursofficial,1790473006906474782,Vic keeps out De Bruyne with a fantastic save! üï∏Ô∏è,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,63,0:0,spursofficial,mancity,0
1695,2024-05-14 20:01:56,spursofficial,1790472634288734716,Back to work in N17 ‚úä,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,61,0:0,spursofficial,mancity,0
1696,2024-05-14 19:46:18,spursofficial,1790468699868025264,Goalless at the interval ‚è∏Ô∏è https://t.co/A1BdU...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,46,0:0,spursofficial,mancity,0
1697,2024-05-14 19:30:54,spursofficial,1790464824863826339,Level after the opening 3Ô∏è‚É£0Ô∏è‚É£ minutes üëä https...,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,30,0:0,spursofficial,mancity,0
1698,2024-05-14 19:18:41,spursofficial,1790461753530163444,üåü https://t.co/9oxvN2NkmA,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,18,0:0,spursofficial,mancity,0
1699,2024-05-14 19:06:07,spursofficial,1790458589666025749,Lolo is denied by a superb Ederson save! üß§,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,6,0:0,spursofficial,mancity,0
1700,2024-05-14 19:05:44,spursofficial,1790458494312710390,ü´∂ https://t.co/859glKQVeP,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,5,0:0,spursofficial,mancity,0
1701,2024-05-14 19:00:22,spursofficial,1790457143465795638,COME ON YOU SPURS! ü§ç,"Tottenham, London, England",/en/matches/2ba17e6d/Tottenham-Hotspur-Manches...,2ba17e6d,2024-05-14 19:00:00,0,0:0,spursofficial,mancity,0

In [257]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,user_description,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",Funniest Michigan Man ever. Also the spinal co...,109.0,False,False,NaN,2ba17e6d,1790486742132216048
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,Funny Clips ‚Ä¢ Funny Quotes ‚Ä¢ @Arsenal üî¥ ‚Ä¢ Ig &...,6970.0,False,False,NaN,2ba17e6d,1790486742132216048
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,The only app you‚Äôll need for 'all things crypt...,5293573.0,False,True,Business,2ba17e6d,1790486742132216048
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,UP THE VILLA! ‚úä,2423724.0,False,True,Business,2ba17e6d,1790486742132216048
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,a chill guy,452.0,False,True,NaN,2ba17e6d,1790486742132216048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,@sheffieldunited | @saints | #NewYorkForever,57.0,False,False,NaN,55fd92c7,1690365565234192385
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,NaN,0.0,False,False,NaN,55fd92c7,1690365565234192385
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,Content Creator | Graphics Designer | Writer |...,2038.0,False,False,NaN,55fd92c7,1690365565234192385
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,Dont believe everything you see on the interne...,94.0,False,False,NaN,55fd92c7,1690365565234192385
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",Exiled Blade. Workaholic. Proud Dad of Joe,312.0,False,False,NaN,55fd92c7,1690365565234192385

In [269]:
replies["margin"] = None
replies["score"] = None
replies["home_team"] = None
replies["away_team"] = None

In [270]:
for i, tweet in replies.iterrows(): 

    parent_tweet = parent_tweets[parent_tweets["tweet_id"] == tweet["parent_tweet_id"]]

    replies.at[i, "margin"] = parent_tweet["margin"].values[0]
    replies.at[i, "score"] = parent_tweet["score"].values[0]
    replies.at[i, "home_team"] = parent_tweet["home_team"].values[0]
    replies.at[i, "away_team"] = parent_tweet["away_team"].values[0]

In [271]:
replies

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team
0,2024-05-14 22:55:03+00:00,@ManCity @okx Thank you @BensonBunnyBoy ‚ù§Ô∏è,1.790516e+18,BigCatsBack,2022-10-14 00:00:44+00:00,en,0.0,NaN,NaN,"Manchester, England",...,109.0,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
1,2024-05-14 21:05:39+00:00,@ManCity @okx https://t.co/fBAOtiLNLp,1.790489e+18,MalekTrendz,2017-10-12 10:01:10+00:00,qme,1.0,NaN,NaN,NaN,...,6970.0,False,False,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
2,2024-05-14 21:10:35+00:00,@ManCity way to go on the Wüî•üíô,1.790490e+18,okx,2017-05-25 05:46:29+00:00,en,22.0,NaN,NaN,NaN,...,5293573.0,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
3,2024-05-14 21:07:09+00:00,@ManCity @okx Nice one,1.790489e+18,AVFCOfficial,2009-03-29 19:48:01+00:00,en,7114.0,NaN,NaN,Villa Park,...,2423724.0,False,True,Business,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
4,2024-05-14 20:59:43+00:00,@ManCity @okx ü´°ü´°ü©µü©µü©µü©µü©µü©µ,1.790487e+18,Ryan_Gwane,2015-03-19 01:31:39+00:00,qme,2.0,NaN,NaN,United Kingdom,...,452.0,False,True,NaN,2ba17e6d,1790486742132216048,2,0:2,spursofficial,mancity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79572,2023-08-12 14:13:34+00:00,@SheffieldUnited @WilliamOsula Osula looks gre...,1.690366e+18,MattUTB,2018-02-06 04:23:19+00:00,en,2.0,NaN,NaN,NaN,...,57.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79573,2023-08-12 14:21:30+00:00,@SheffieldUnited @WilliamOsula More dangerous ...,1.690368e+18,AshleyFoth99234,2023-07-06 10:27:08+00:00,en,0.0,NaN,NaN,NaN,...,0.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79574,2023-08-12 14:13:11+00:00,@SheffieldUnited @WilliamOsula Score some please,1.690366e+18,judelucan,2017-11-27 21:09:28+00:00,en,0.0,NaN,NaN,Nigeria,...,2038.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79575,2023-08-12 14:13:13+00:00,@SheffieldUnited @WilliamOsula Can anyone tell...,1.690366e+18,Adamsablade,2020-09-04 11:31:40+00:00,en,0.0,NaN,NaN,NaN,...,94.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc
79576,2023-08-12 16:11:02+00:00,@SheffieldUnited @WilliamOsula Osula need McBu...,1.690395e+18,PagsBlade,2017-05-17 23:51:33+00:00,en,0.0,NaN,NaN,"Orlando, FL",...,312.0,False,False,NaN,55fd92c7,1690365565234192385,0,0:0,sheffieldunited,cpfc

In [272]:
replies["margin"].unique()

array([2, 1, 0, 4, 3, -1, 5, -2, 6, -3, -4, -5, 8, 7, -6, -8, -7],
      dtype=object)

In [273]:
replies[replies["margin"].isin([8, -8])]

,datetime,tweet,id,user_handle,created,lang,likes,place,coords,user_location,...,user_followers,user_verified,user_blue,user_blue_type,report_id,parent_tweet_id,margin,score,home_team,away_team
32905,2023-09-24 17:27:55+00:00,@NUFC Could of been a bit more clinical today ...,1.705998e+18,TheMasterBucks,2010-09-28 09:01:54+00:00,en,86.0,NaN,NaN,"Adelaide, South Australia",...,71397.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32906,2023-09-24 17:28:03+00:00,@NUFC Tears Newcastle have scored more goals i...,1.705998e+18,PovertykillerB,2021-09-15 06:58:24+00:00,en,216.0,NaN,NaN,"Cape Town, South Africa",...,129481.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32907,2023-09-24 17:30:41+00:00,@NUFC Highlights of the gameüòÇ https://t.co/JsS...,1.705998e+18,PovertykillerB,2021-09-15 06:58:24+00:00,en,84.0,NaN,NaN,"Cape Town, South Africa",...,129481.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32908,2023-09-24 17:28:54+00:00,@NUFC üôåüôåüôå,1.705998e+18,viperioesports,2013-02-01 21:18:57+00:00,qme,4.0,NaN,NaN,"Newcastle, UK",...,7952.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32909,2023-09-24 17:27:55+00:00,@NUFC You have 3 losses üò≠üò≠üò≠üò≠üò≠ same as Chelsea,1.705998e+18,CFCA1_,2022-02-22 20:47:54+00:00,en,3.0,NaN,NaN,"London, England",...,2546.0,False,False,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32910,2023-09-24 17:51:17+00:00,@NUFC What. A. Game.\n\nüëè‚ö´Ô∏è‚ö™Ô∏è,1.706003e+18,NU_Foundation,2011-06-04 07:56:56+00:00,en,27.0,NaN,NaN,NUCASTLE,...,24957.0,False,True,Business,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32911,2023-09-24 17:28:44+00:00,@NUFC https://t.co/Wy9K3AB9Q2,1.705998e+18,Memecastle_Utd,2021-11-09 12:36:39+00:00,qme,526.0,NaN,NaN,"Newcastle Upon Tyne, England",...,13685.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32912,2023-09-24 17:28:59+00:00,@NUFC Hi @NUFC don‚Äôt you want to loan some of ...,1.705998e+18,BlessedUtd,2012-12-22 18:08:49+00:00,en,11.0,NaN,NaN,NaN,...,11551.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32913,2023-09-24 17:32:25+00:00,@NUFC Can we play a champions league game ever...,1.705999e+18,XrpNufcFanRich,2019-05-18 17:38:36+00:00,en,0.0,NaN,NaN,NaN,...,287.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32914,2023-09-24 17:29:50+00:00,@NUFC Just 1 goal away from equalling the reco...,1.705998e+18,elliotraiX,2012-04-05 05:40:16+00:00,en,1.0,NaN,NaN,"London, England",...,321.0,False,True,NaN,cf4fef85,1705997427923140927,8,0:8,sheffieldunited,nufc
32915,2023-09-24 17:20:49+00:00,@NUFC win probability updating https://t.co/9h...,1.705996e+18,theschmaltz1,2017-06-13 22:03:47+00:00,en,23.0,NaN,NaN,After Shachris,...,2239.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32916,2023-09-24 17:20:16+00:00,@NUFC Cheers Isak had the 7up meme ready to go...,1.705996e+18,TheMasterBucks,2010-09-28 09:01:54+00:00,en,22.0,NaN,NaN,"Adelaide, South Australia",...,71394.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32917,2023-09-24 17:21:51+00:00,@NUFC https://t.co/DbhPjLPyMd,1.705996e+18,Memecastle_Utd,2021-11-09 12:36:39+00:00,qme,106.0,NaN,NaN,"Newcastle Upon Tyne, England",...,13686.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32918,2023-09-24 17:21:11+00:00,@NUFC More more more!,1.705996e+18,SavMondo,2020-03-25 17:54:34+00:00,en,14.0,NaN,NaN,In disguise @ Emirates Stadium,...,42474.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32919,2023-09-24 17:22:05+00:00,@NUFC This is haram football üòÇ,1.705996e+18,simeontobi0,2013-08-12 23:16:21+00:00,en,0.0,NaN,NaN,NaN,...,3279.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32920,2023-09-24 17:20:31+00:00,@NUFC Eight ???? üôÜüèæ‚Äç‚ôÇÔ∏è,1.705996e+18,Mr_Jibzz,2011-07-13 12:33:35+00:00,en,1.0,NaN,NaN,NaN,...,8067.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32921,2023-09-24 17:20:17+00:00,@NUFC ŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸáŸá...,1.705996e+18,o887p,2021-09-20 20:42:07+00:00,ar,0.0,NaN,NaN,NaN,...,752.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32922,2023-09-24 17:20:21+00:00,@NUFC https://t.co/A0XR9QVZCN,1.705996e+18,o887p,2021-09-20 20:42:07+00:00,qme,0.0,NaN,NaN,NaN,...,752.0,False,True,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32923,2023-09-24 17:23:47+00:00,@NUFC Lots of teams without 8 all season....,1.705996e+18,StolenStones1,2011-11-11 23:08:27+00:00,en,0.0,NaN,NaN,"Kl√¶bu, Norge",...,694.0,False,False,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32924,2023-09-24 17:23:51+00:00,@NUFC Fuckin insane,1.705996e+18,Harxl05,2021-01-12 07:43:59+00:00,en,0.0,NaN,NaN,NaN,...,33.0,False,False,NaN,cf4fef85,1705995450954744237,8,0:8,sheffieldunited,nufc
32925,2023-09-24 17:18:53+00:00,@NUFC wow!,1.705995e+18,theschmaltz1,2017-06-13 22:03:47+00:00,und,0.0,NaN,NaN,After Shachris,...,2239.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32926,2023-09-24 17:19:11+00:00,@NUFC WE FUCKING ATE üôå,1.705995e+18,TheMasterBucks,2010-09-28 09:01:54+00:00,en,14.0,NaN,NaN,"Adelaide, South Australia",...,71397.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32927,2023-09-24 17:21:07+00:00,@NUFC https://t.co/6fmc2IHTxJ,1.705996e+18,Memecastle_Utd,2021-11-09 12:36:39+00:00,qme,114.0,NaN,NaN,"Newcastle Upon Tyne, England",...,13685.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32928,2023-09-24 17:22:22+00:00,"@NUFC 8 goals, 8 different scorers. Sure this ...",1.705996e+18,Shawnifee,2017-11-07 13:12:46+00:00,en,43.0,NaN,NaN,Lagos - New York - Manchester,...,146954.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32929,2023-09-24 17:18:20+00:00,@NUFC 2 more. Possible?,1.705995e+18,ForeverBlue_07,2014-01-20 07:39:21+00:00,en,13.0,NaN,NaN,London,...,6766.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32930,2023-09-24 17:18:42+00:00,@NUFC GUYS I LOVE YOU ALLLL,1.705995e+18,agbnufc_,2020-06-15 16:23:05+00:00,en,57.0,NaN,NaN,US,...,17834.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32931,2023-09-24 17:18:55+00:00,@NUFC Sweet lord,1.705995e+18,FtblJoe,2015-06-09 02:14:08+00:00,en,18.0,NaN,NaN,NaN,...,10017.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32932,2023-09-24 17:19:30+00:00,@NUFC My god he is so good,1.705995e+18,nufc_rockets,2020-02-17 15:12:46+00:00,en,4.0,NaN,NaN,United Kingdom,...,1107.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32933,2023-09-24 17:37:56+00:00,@NUFC Conclusion : this team only will play we...,1.706000e+18,sergioa94679493,2022-08-30 01:20:48+00:00,en,0.0,NaN,NaN,"Barranquilla, Colombia",...,27248.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32934,2023-09-24 18:02:08+00:00,@NUFC My star boy,1.706006e+18,OxRonin_,2020-05-20 19:43:57+00:00,en,0.0,NaN,NaN,Dojo,...,2466.0,False,True,NaN,cf4fef85,1705995056539115564,8,0:8,sheffieldunited,nufc
32935,2023-09-24 17:13:17+00:00,@NUFC https://t.co/uPJ1X3vkWm,1.705994e+18,SavMondo,2020-03-25 17:54:34+00:00,qme,10.0,NaN,NaN,In disguise @ Emirates Stadium,...,42468.0,False,True,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32936,2023-09-24 17:12:48+00:00,@NUFC Lewis Hall exists üî•,1.705994e+18,agbnufc_,2020-06-15 16:23:05+00:00,en,42.0,NaN,NaN,US,...,17834.0,False,True,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32937,2023-09-24 17:13:28+00:00,@NUFC Finally,1.705994e+18,obeadmowail,2011-03-11 11:45:28+00:00,en,0.0,NaN,NaN,Kuwait,...,2108.0,False,True,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32938,2023-09-24 17:12:42+00:00,@NUFC üñ§üñ§üñ§,1.705994e+18,__1927it,2014-05-16 12:19:30+00:00,qme,0.0,NaN,NaN,ÿ£ŸäŸÜŸÖÿß Ÿàÿ¨ÿØ ÿßŸÑÿßÿ™ÿ≠ÿßÿØ Ÿà ŸÜŸäŸàŸÉÿßÿ≥ŸÑ.,...,29822.0,False,True,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32939,2023-09-24 17:14:05+00:00,@NUFC What does burn have to do for a breather...,1.705994e+18,NwoahmD,2020-08-05 22:08:55+00:00,en,0.0,NaN,NaN,St James‚Äô Park,...,408.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32940,2023-09-24 17:16:59+00:00,@NUFC https://t.co/sKufJfjKsH,1.705995e+18,WeAllLoveNUFC,2021-11-21 07:29:58+00:00,qme,0.0,NaN,NaN,NaN,...,329.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32941,2023-09-24 17:13:54+00:00,@NUFC ‚Äú¬£65million on the bench‚Äù shut up üòÇ,1.705994e+18,ryandavid97,2012-03-24 21:36:29+00:00,en,1.0,NaN,NaN,"Newcastle Upon Tyne, England",...,270.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32942,2023-09-24 17:12:40+00:00,@NUFC fucking finally,1.705994e+18,jacobmurphygoat,2023-05-23 23:48:54+00:00,en,1.0,NaN,NaN,NaN,...,259.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32943,2023-09-24 17:16:42+00:00,@NUFC Popes went to sleep bless,1.705995e+18,BTBI08,2022-11-04 21:14:41+00:00,en,0.0,NaN,NaN,NaN,...,63.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
32944,2023-09-24 17:12:56+00:00,@NUFC HES ALIVEEEEE,1.705994e+18,BellsyNUFC,2020-04-27 13:01:51+00:00,en,3.0,NaN,NaN,Livramento's Back Pocket,...,1524.0,False,False,NaN,cf4fef85,1705993626386395442,8,0:8,sheffieldunited,nufc
78710,2023-09-24 17:27:36+00:00,@SheffieldUnited It‚Äôs official! Sheffield Unit...,1.705997e+18,CFCA1_,2022-02-22 20:47:54+00:00,en,1032.0,NaN,NaN,"London, England",...,2549.0,False,False,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78711,2023-09-24 17:36:48+00:00,@SheffieldUnited @AllanNyash How many üòÇüòÇüòÇüòÇ,1.706000e+18,adan_zamuh,2019-03-15 10:49:33+00:00,en,0.0,NaN,NaN,Eastleigh,...,127367.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78712,2023-09-24 17:39:11+00:00,@SheffieldUnited @AllanNyash Your premier leag...,1.706000e+18,adan_zamuh,2019-03-15 10:49:33+00:00,en,10.0,NaN,NaN,Eastleigh,...,127367.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78713,2023-09-24 17:40:21+00:00,@SheffieldUnited Fair play on last season! But...,1.706001e+18,Baggieboy75Mike,2011-12-24 19:57:40+00:00,en,0.0,NaN,NaN,"Shifnal, England",...,582.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78714,2023-09-24 17:41:25+00:00,@SheffieldUnited I‚Äôll jump off a bridge,1.706001e+18,johncam1889,2021-01-06 18:15:15+00:00,en,0.0,NaN,NaN,Bramall Lane,...,877.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78715,2023-09-24 17:46:35+00:00,@SheffieldUnited Newcastle ate ü§å,1.706002e+18,aey_dear,2012-01-23 22:15:28+00:00,en,3.0,NaN,NaN,"Polokwane, South Africa",...,87572.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78716,2023-09-24 17:27:35+00:00,@SheffieldUnited Southampton fans had notis on...,1.705997e+18,Saltyfootball7,2022-04-18 10:45:01+00:00,en,33.0,NaN,NaN,"London, England",...,723.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78717,2023-09-24 17:27:40+00:00,@SheffieldUnited Sheffield United in the PL ht...,1.705997e+18,ForeverBlue_07,2014-01-20 07:39:21+00:00,en,1827.0,NaN,NaN,London,...,6771.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78718,2023-09-24 17:28:00+00:00,@SheffieldUnited No scoreline no graphics. Adm...,1.705998e+18,ForeverBlue_07,2014-01-20 07:39:21+00:00,en,3102.0,NaN,NaN,London,...,6771.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc
78719,2023-09-24 17:28:50+00:00,@SheffieldUnited Which United? Tell us the score,1.705998e+18,joshpearson180,2012-02-17 22:49:32+00:00,en,73.0,NaN,NaN,B town,...,27640.0,False,True,NaN,cf4fef85,1705997391785075106,-8,0:8,sheffieldunited,nufc

In [274]:
replies.to_csv("REPLIES_FINAL.csv", index=False)

/home/jasmine/miniconda3/lib/python3.11/site-packages/pandas/core/internals/blocks.py:2538: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)